'use client';
import {useState} from 'react';
import {Check,X,Plus,Play} from 'lucide-react';
import {findTaxonomy,namespaceNames,tagById,taxonomyNamespaces} from '@/lib/taxonomy';
import type {Tagging,TagAssignment} from '@/lib/tagging';
import type {AnalysisReport} from '@/lib/analysis/types';
import type {SearchOptions} from '@/lib/clips';
import {timecode} from '@/lib/segments';
function Picker({onPick,disabled}:{onPick:(id:string)=>void;disabled?:boolean}){
 const[query,setQuery]=useState(''),[namespace,setNamespace]=useState('');const results=findTaxonomy(query,namespace);
 return <details className="taxonomy-picker"><summary>표준 태그 검색해서 추가</summary><div className="taxonomy-controls"><input aria-label="표준 태그 검색" value={query} onChange={e=>setQuery(e.target.value)} placeholder="RGB Shift, Glitch…" maxLength={100}/><select aria-label="태그 추가 분류" value={namespace} onChange={e=>setNamespace(e.target.value)}><option value="">전체 분류</option>{taxonomyNamespaces.map(n=><option key={n.id} value={n.id}>{namespaceNames[n.id]}</option>)}</select></div><div className="taxonomy-options">{results.slice(0,24).map(t=><button type="button" disabled={disabled} key={t.id} onClick={()=>onPick(t.id)} aria-label={`${t.display_name} · ${namespaceNames[t.namespace]} 추가`}><span>{t.display_name}<small>{namespaceNames[t.namespace]}{!t.observable?' · 제작 방식 추정':''}</small></span><Plus size={16}/></button>)}</div><p className="form-note">{results.length}개 중 {Math.min(24,results.length)}개 표시 · 분류와 별칭으로 좁혀보세요.</p></details>;
}
export function TagReview({value,onDecision,onEvidence,disabled=false}:{value:Tagging;onDecision:(id:string,status:'accepted'|'rejected')=>void;onEvidence?:(seconds:number)=>void;disabled?:boolean}){
 const[showRejected,setShowRejected]=useState(false);const counts=(status:string)=>value.assignments.filter(a=>a.status===status).length;
 function row(a:TagAssignment){const tag=tagById.get(a.tagId)!;return <div className={'taxonomy-row '+a.status} key={a.tagId}><div className="taxonomy-tag-heading"><strong>{tag.display_name}</strong><span>{namespaceNames[tag.namespace]}</span></div><p className="taxonomy-provenance">{a.source==='user'?'직접 추가':a.source==='ai_inferred'?'AI 추정':'AI 관찰'}{a.aiScore!==null?` · AI 점수 ${a.aiScore.toFixed(2)}`:''}{a.decisionBy==='user'?' · 사용자 결정':''}</p><div className="taxonomy-row-bottom"><div className="taxonomy-evidence">{a.evidenceMs.slice(0,4).map(t=><button type="button" key={t} disabled={!onEvidence} onClick={()=>onEvidence?.(t/1000)} aria-label={`${tag.display_name} 근거 ${timecode(t/1000)} 재생`}><Play size={11}/>{timecode(t/1000)}</button>)}</div><div className="taxonomy-decisions">{a.status!=='accepted'&&<button type="button" disabled={disabled} onClick={()=>onDecision(a.tagId,'accepted')} aria-label={`${tag.display_name} · ${namespaceNames[tag.namespace]} 승인`}><Check size={13}/>승인</button>}{a.status!=='rejected'&&<button type="button" disabled={disabled} onClick={()=>onDecision(a.tagId,'rejected')} aria-label={`${tag.display_name} · ${namespaceNames[tag.namespace]} 거절`}><X size={13}/>{a.status==='accepted'?'제외':'거절'}</button>}</div></div></div>;}
 return <section className="tag-review" aria-label="표준 태그 검수"><div className="segment-heading"><h3>표준 태그 <span>{counts('accepted')} 확정</span></h3><small>사전 v{value.taxonomyVersion}</small></div><p className="form-note">관찰 가능한 태그는 자동 분류하고, 제작 방식·불확실한 태그는 제안으로 남겨요. AI 점수는 정확도 확률이 아니에요. 승인·거절은 재분석해도 유지돼요.</p>{counts('suggested')>0&&<div className="taxonomy-section"><h4>검수할 AI 제안 <span>{counts('suggested')}</span></h4>{value.assignments.filter(a=>a.status==='suggested').map(row)}</div>}<div className="taxonomy-section"><h4>확정 태그</h4>{value.assignments.filter(a=>a.status==='accepted').map(row)}{!counts('accepted')&&<p className="form-note">확정된 표준 태그가 없어요. 기존 직접 입력 태그는 그대로 유지돼요.</p>}</div>{counts('rejected')>0&&<><button type="button" className="subtle-button" onClick={()=>setShowRejected(v=>!v)}>제외한 태그 {counts('rejected')}개 {showRejected?'접기':'보기'}</button>{showRejected&&value.assignments.filter(a=>a.status==='rejected').map(row)}</>}<Picker disabled={disabled} onPick={id=>onDecision(id,'accepted')}/></section>;
}
export function TaxonomyFilters({value,onChange}:{value:SearchOptions;onChange:(value:SearchOptions)=>void}){
 const[query,setQuery]=useState(''),[namespace,setNamespace]=useState('');const ids=value.canonicalIds||[];const toggle=(id:string)=>onChange({...value,canonicalIds:ids.includes(id)?ids.filter(t=>t!==id):[...ids,id]});const results=findTaxonomy(query,namespace);
 return <details className="taxonomy-search"><summary>표준 태그로 찾기 <span>12개 분류 · 별칭 · 하위 태그{ids.length?` · ${ids.length}개 선택`:''}</span></summary><div className="taxonomy-controls"><input value={query} onChange={e=>setQuery(e.target.value)} aria-label="태그 필터 검색" placeholder="태그 이름 또는 별칭 검색" maxLength={100}/><select aria-label="검색할 태그 분류" value={namespace} onChange={e=>setNamespace(e.target.value)}><option value="">전체 분류</option>{taxonomyNamespaces.map(n=><option key={n.id} value={n.id}>{namespaceNames[n.id]}</option>)}</select></div><div className="taxonomy-controls"><label>태그 조합<select aria-label="태그 조합 방식" value={value.mode||'and'} onChange={e=>onChange({...value,mode:e.target.value as 'and'|'or'})}><option value="and">모두 포함 (AND)</option><option value="or">하나 이상 (OR)</option></select></label><label>검수 상태<select aria-label="검수 상태 필터" value={value.review||'all'} onChange={e=>onChange({...value,review:e.target.value as SearchOptions['review']})}><option value="all">전체 클립</option><option value="suggested">AI 제안이 남은 클립</option><option value="user">사용자 확정 태그가 있는 클립</option></select></label></div><div className="chips">{ids.map(id=><button type="button" className="chip selected" key={id} onClick={()=>toggle(id)}>{tagById.get(id)?.display_name||namespaceNames[id.split('.')[0]]} ×</button>)}</div>{namespace&&<button type="button" className={'chip '+(ids.includes(namespace+'.root')?'selected':'')} onClick={()=>toggle(namespace+'.root')}>{namespaceNames[namespace]} 전체 (하위 태그 포함)</button>}<div className="taxonomy-options">{results.slice(0,24).map(t=><button type="button" role="checkbox" aria-checked={ids.includes(t.id)} className={ids.includes(t.id)?'selected':''} key={t.id} onClick={()=>toggle(t.id)}><span>{t.display_name}<small>{namespaceNames[t.namespace]}</small></span>{ids.includes(t.id)?<Check size={15}/>:<Plus size={15}/>}</button>)}</div><p className="form-note">{results.length}개 중 {Math.min(24,results.length)}개 표시 · 확정 태그와 효과 구간을 검색하며 상위 태그는 하위 태그도 포함해요.</p></details>;
}
export function AnalysisHistory({reports}:{reports:AnalysisReport[]}){if(!reports.length)return null;return <details className="analysis-history"><summary>분석 이력 {reports.length}개</summary>{[...reports].reverse().map((r,i)=><div key={r.analyzedAt+'-'+i}><strong>{new Date(r.analyzedAt).toLocaleString('ko-KR')}</strong><p>{r.engine==='gemini-video-v1'?'Gemini':r.engine==='openai-frames-v1'?'OpenAI':'이전 분석'} · {r.tagging?`사전 ${r.tagging.taxonomyVersion}`:'자유 태그'} · {r.promptVersion||'이전 프롬프트'}</p><div className="chips">{r.tagging?.assignments.slice(0,12).map(a=><span className="chip" key={a.tagId}>{tagById.get(a.tagId)?.display_name}</span>)}</div><p className="form-note">{r.notes[1]||r.notes[0]}</p></div>)}<p className="form-note">최근 10개의 저장된 분석 결과를 보관해요. 이력은 현재 검수 결정을 바꾸지 않아요.</p></details>;}
