import assert from 'node:assert/strict';
import {applyOrder,replaceVisibleOrder,moveKey,parseOrderChange} from '../../apps/web/features/library/library-order';
import {discoveryProfile,discoveryIdentity} from '../../apps/web/features/discovery/discovery-profile';
import {youtubeSource,groundedCandidates,verifyYouTube} from '../../apps/web/lib/ai/youtube-discovery';
import {emptyTagging,type TagAssignment} from '../../apps/web/lib/tagging';
import type {Clip} from '../../apps/web/lib/clips';
const blank={color:[],shot:[],effect:[]};
const assignment=(tagId:string,status:TagAssignment['status']='accepted'):TagAssignment=>({tagId,status,source:'user',decisionBy:'user',evidenceMs:[],aiScore:null});
const clip=(id:string,extra:Partial<Clip>={}):Clip=>({id,title:'private title',notes:'private memo',sourceUrl:'',videoUrl:null,posterUrl:null,tags:blank,createdAt:'2026-09-29',...extra});
assert.deepEqual(replaceVisibleOrder(['a','hidden1','b','hidden2','c'],['c','a','b']),['c','hidden1','a','hidden2','b']);
assert.deepEqual(applyOrder(['new','a','b'],['b','a'],v=>v),['new','b','a']);
assert.deepEqual(moveKey(['a','b','c'],'c','a'),['c','a','b']);
assert.throws(()=>parseOrderChange({scope:'videos',revision:0,keys:['a','a']}));
assert.throws(()=>parseOrderChange({scope:'segments',revision:0,keys:['a']}));
assert.equal(parseOrderChange({scope:'segments',revision:3,keys:['c/s']}).revision,3);
const segment={id:'s',startSeconds:0,endSeconds:2,effects:[],note:'',tags:blank,tagging:{...emptyTagging(),assignments:[assignment('color.blue')]}};
const single=clip('a',{segments:[segment]});
assert.deepEqual(discoveryProfile([single]).tags,discoveryProfile([{...single,segments:Array.from({length:30},(_,i)=>({...segment,id:'s'+i}))}]).tags);
const rejected=clip('a',{tags:{...blank,color:['blue']},tagging:{...emptyTagging(),assignments:[assignment('color.blue','rejected')]}});
assert.equal(discoveryProfile([rejected]).tags.length,0);
assert.equal(discoveryProfile([{...rejected,tagging:{...emptyTagging(),assignments:[assignment('color.blue','suggested')]}}]).tags.length,0);
assert.equal(discoveryProfile([clip('s',{tags:{...blank,shot:['close-up']}})]).tags[0].id,'shot_type.close_up');
const saved='abcdefghijk',fresh='lmnopqrstuv',short='0123456789_';
assert.equal(discoveryProfile([clip('a',{sourceUrl:'https://youtu.be/'+saved,segments:[segment]}),clip('b',{sourceUrl:'https://www.youtube.com/shorts/'+saved,segments:[segment]})]).sourceCount,1);
assert(!discoveryIdentity(discoveryProfile([single])).includes('private'));
assert.equal(youtubeSource('https://youtube.com.attacker.test/watch?v='+saved),null);
assert.equal(youtubeSource('https://www.youtube.com/watch?v='+saved+'&v='+fresh),null);
assert.equal(youtubeSource('https://user@youtube.com/watch?v='+saved),null);
const profile=discoveryProfile([clip('a',{sourceUrl:'https://youtu.be/'+saved})]);
const output={status:'completed',output:[{type:'web_search_call',action:{sources:[{url:'https://www.youtube.com/watch?v='+saved},{url:'https://www.youtube.com/watch?v='+fresh},{url:'https://www.youtube.com/shorts/'+short}]}},{type:'message',content:[{type:'output_text',text:JSON.stringify({items:[{url:'https://youtu.be/'+saved,group:'similar',reason:'saved'},{url:'https://youtube.com/watch?v=notgrounded',group:'similar',reason:'invented'},{url:'https://www.youtube.com/shorts/'+fresh,group:'similar',reason:'watch source'},{url:'https://www.youtube.com/watch?v='+short,group:'explore',reason:'short source'},{url:'https://youtu.be/'+short,group:'similar',reason:'duplicate'}]})}]}]};
const candidates=groundedCandidates(output,profile,'all');assert.equal(candidates.length,2);assert.equal(candidates[0].shorts,false);assert.equal(candidates[1].shorts,true);
assert.deepEqual(groundedCandidates(output,profile,'shorts').map(c=>c.id),[short]);
assert.throws(()=>groundedCandidates({...output,output:output.output.slice(1)},profile,'all'));
const original=globalThis.fetch;globalThis.fetch=async()=>Response.json({type:'video',title:'Verified title',author_name:'Creator'});
assert.equal((await verifyYouTube(candidates[0],new AbortController().signal))?.title,'Verified title');
globalThis.fetch=async()=>new Response('Error',{status:404});assert.equal(await verifyYouTube(candidates[0],new AbortController().signal),null);globalThis.fetch=original;
console.log('PASS: ordering, hidden slots, source weighting, review decisions, privacy, grounded URLs, Shorts identity, oEmbed errors (20 checks)');
