import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {env} from './mock-cloudflare';
import {PATCH} from '../../apps/web/app/api/clips/[id]/route';
import {serialize} from '../../apps/web/lib/server';
const sql=new DatabaseSync(':memory:');
for(const file of readdirSync('apps/web/drizzle').filter(name=>name.endsWith('.sql')).sort())sql.exec(readFileSync('apps/web/drizzle/'+file,'utf8'));
let beforeRun:undefined|((query:string,values:any[])=>Promise<void>|void);
env.DB={prepare(query:string){return{bind(...values:any[]){return{async first(){return sql.prepare(query).get(...values)||null;},async all(){return{results:sql.prepare(query).all(...values)};},async run(){await beforeRun?.(query,values);return{meta:{changes:Number(sql.prepare(query).run(...values).changes)}};}};}};}};
env.BUCKET={async delete(){}};
const segment=(id:string,start:number)=>({id,startSeconds:start,endSeconds:start+2,title:id,effects:[],note:'',tags:{color:[],shot:[],effect:[]}});
const segments=[segment('s1',0),segment('s2',2),segment('s3',4)];
function reset(){beforeRun=undefined;sql.exec('DELETE FROM segment_media');sql.exec('DELETE FROM clips');sql.prepare('INSERT INTO clips(id,title,source_url,tags,notes,created_at,segments,revision) VALUES (?,?,?,?,?,?,?,?)').run('fixture','original title','https://example.org/video',JSON.stringify({color:['blue'],shot:[],effect:[]}),'original memo','2026-09-29',JSON.stringify(segments),0);}
const row=()=>sql.prepare('SELECT * FROM clips WHERE id=?').get('fixture') as any;
async function patch(body:any){const response=await PATCH(new Request('http://localhost/api/clips/fixture',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),{params:Promise.resolve({id:'fixture'})});return{status:response.status,data:await response.json() as any};}
const favorite=(favorite:boolean,segmentId?:string)=>patch({favoriteChange:{favorite,...(segmentId===undefined?{}:{segmentId})}});
const savedIds=()=>JSON.parse(row().favorite_segments) as string[];
let passes=0,failures=0;
async function test(name:string,fn:()=>Promise<void>){reset();try{await fn();passes++;console.log('PASS',name);}catch(e){failures++;console.error('FAIL',name,':',(e as Error).message);}}
await test('Video favorite set/unset preserves metadata and revision',async()=>{for(const value of [true,false]){const res=await favorite(value);assert.equal(res.status,200);assert.equal(res.data.favorite,value);assert.deepEqual(Object.keys(res.data).sort(),['favorite','favoriteSegmentIds']);assert.equal(row().revision,0);assert.equal(row().notes,'original memo');assert.equal(row().title,'original title');assert.deepEqual(savedIds(),[]);}});
await test('Video and three segment favorites are independent',async()=>{await favorite(true);await favorite(true,'s1');await favorite(true,'s2');await favorite(true,'s3');await favorite(false,'s2');assert.equal(row().favorite,1);assert.deepEqual(savedIds().sort(),['s1','s3']);await favorite(false);assert.deepEqual(savedIds().sort(),['s1','s3']);assert.equal(row().revision,0);});
await test('Repeated segment add/remove is idempotent',async()=>{await favorite(true,'s1');await favorite(true,'s1');assert.deepEqual(savedIds(),['s1']);await favorite(false,'s1');await favorite(false,'s1');assert.deepEqual(savedIds(),[]);});
await test('Concurrent additions retain distinct IDs and do not duplicate one ID',async()=>{const responses=await Promise.all([favorite(true,'s1'),favorite(true,'s2'),favorite(true,'s1')]);assert(responses.every(r=>r.status===200));assert.deepEqual(savedIds().sort(),['s1','s2']);assert.equal(row().revision,0);});
await test('Concurrent removal and addition preserve unrelated selections',async()=>{await favorite(true,'s1');await favorite(true,'s3');const responses=await Promise.all([favorite(false,'s1'),favorite(true,'s2')]);assert(responses.every(r=>r.status===200));assert.deepEqual(savedIds().sort(),['s2','s3']);});
await test('Invalid and mixed favorite commands are rejected without mutation',async()=>{for(const body of [{favoriteChange:null},{favoriteChange:[]},{favoriteChange:{}},{favoriteChange:{favorite:'true'}},{favoriteChange:{favorite:true,segmentId:''}},{favoriteChange:{favorite:true,segmentId:'../bad'}},{favoriteChange:{favorite:true,segmentId:12}},{favoriteChange:{favorite:true},notes:'must not write'}]){const res=await patch(body);assert.equal(res.status,400,JSON.stringify(body));assert.equal(row().favorite,0);assert.equal(row().notes,'original memo');assert.equal(row().revision,0);assert.deepEqual(savedIds(),[]);}});
await test('Nonexistent segment cannot become a favorite',async()=>{const res=await favorite(true,'not-existing');assert(res.status===404||res.status===409);assert.deepEqual(savedIds(),[]);});
await test('Metadata edit retains video/segment favorites and returns them',async()=>{await favorite(true);await favorite(true,'s1');const res=await patch({notes:'new memo',revision:0});assert.equal(res.status,200);assert.equal(res.data.clip.favorite,true);assert.deepEqual(res.data.clip.favoriteSegmentIds,['s1']);assert.equal(row().revision,1);assert.equal(row().notes,'new memo');assert.deepEqual(savedIds(),['s1']);});
await test('Removing a segment retires only its favorite',async()=>{await favorite(true,'s1');await favorite(true,'s2');const res=await patch({segments:segments.filter(s=>s.id!=='s1'),revision:0});assert.equal(res.status,200);assert.deepEqual(savedIds(),['s2']);assert.deepEqual(res.data.clip.favoriteSegmentIds,['s2']);});
await test('Favorites committed after metadata snapshot survive atomic metadata update',async()=>{beforeRun=async query=>{if(!query.startsWith('UPDATE clips SET title'))return;beforeRun=undefined;assert.equal((await favorite(true)).status,200);assert.equal((await favorite(true,'s2')).status,200);};const res=await patch({notes:'overlap memo',revision:0});assert.equal(res.status,200);assert.equal(row().favorite,1);assert.deepEqual(savedIds(),['s2']);assert.equal(res.data.clip.favorite,true);assert.deepEqual(res.data.clip.favoriteSegmentIds,['s2']);assert.equal(row().notes,'overlap memo');assert.equal(row().revision,1);});
await test('Favorite cannot reinsert a segment removed after its initial read',async()=>{beforeRun=query=>{if(!query.startsWith('UPDATE clips SET'))return;beforeRun=undefined;sql.prepare('UPDATE clips SET segments=?,revision=revision+1 WHERE id=?').run(JSON.stringify(segments.filter(s=>s.id!=='s1')),'fixture');};const res=await favorite(true,'s1');assert(res.status===404||res.status===409);assert.deepEqual(savedIds(),[]);assert.equal(row().revision,1);});
await test('A star request never resets a metadata update committed during its run',async()=>{beforeRun=query=>{if(!query.startsWith('UPDATE clips SET'))return;beforeRun=undefined;sql.prepare('UPDATE clips SET notes=?,revision=revision+1 WHERE id=?').run('concurrent memo','fixture');};const res=await favorite(true,'s1');assert.equal(res.status,200);assert.equal(row().notes,'concurrent memo');assert.equal(row().revision,1);assert.deepEqual(res.data,{favorite:false,favoriteSegmentIds:['s1']});});
await test('Serialization excludes removed segment IDs without affecting valid selection',async()=>{sql.prepare('UPDATE clips SET favorite_segments=? WHERE id=?').run(JSON.stringify(['ghost','s2']),'fixture');const clip=serialize(row());assert.deepEqual(clip.favoriteSegmentIds,['s2']);});
console.log(JSON.stringify({passes,failures}));sql.close();if(failures)process.exitCode=1;
