import assert from 'node:assert/strict';
import {imageTags,parseImageQuery,rankImageSegments,searchableSegmentIds} from '../../apps/web/features/discovery/image-search';
import {parseSearchImage,imageRequest,parseImageResponse,IMAGE_BODY_LIMIT} from '../../apps/web/lib/ai/image-query';
import {POST} from '../../apps/web/app/api/ai/image-query/route';
import {filterSegments} from '../../apps/web/features/segments/segment-search';
import {aiTagging,decideTag,emptyTagging} from '../../apps/web/lib/tagging';
import {env} from './mock-cloudflare';
const blank=()=>({color:[],shot:[],effect:[]});
const segment=(id:string,tagId?:string,score=.96):any=>({id,startSeconds:0,endSeconds:5,title:id,note:'',effects:[],tags:blank(),...(tagId?{tagging:aiTagging([{tagId,aiScore:score,evidenceMs:[1000]}],5)}:{})});
const clip=(segments:any[],tagId?:string):any=>({id:'parent',title:'blue person',notes:'',sourceUrl:'https://example.org/v',videoUrl:null,posterUrl:null,tags:tagId?{color:['blue'],shot:[],effect:[]}:blank(),tagging:tagId?aiTagging([{tagId,aiScore:.96,evidenceMs:[1000]}],5):emptyTagging(),segments,createdAt:'2026-09-29'});
const body=(tagId='color.blue',aiScore=.95)=>({imageReadable:true,summary:'파란색 사진',tags:[{tagId,aiScore,reason:'파란 색감이 보임'}]});
const query=()=>parseImageQuery(JSON.stringify(body()));
const fixtureImage='data:image/jpeg;base64,/9j/'+ 'A'.repeat(80);
let passed=0,failed=0;
async function test(name:string,fn:()=>void|Promise<void>){try{await fn();passed++;console.log('PASS',name);}catch(e){failed++;console.error('FAIL',name,':',(e as Error).message);}}
await test('Parent title and parent tags never create a segment match',()=>{assert.equal(rankImageSegments(filterSegments([clip([segment('empty')],'color.blue')],'',[]),query()).length,0);});
await test('Only matching interval appears, independent of neighbor tags',()=>{const c=clip([segment('blue','color.blue'),segment('red','color.red'),segment('empty')]);assert.deepEqual(rankImageSegments(filterSegments([c],'',[]),query()).map(x=>x.segment.id),['blue']);});
await test('Suggested and rejected own tags are excluded even when free labels remain',()=>{const suggested=segment('suggested','color.blue',.7),rejected=segment('rejected','color.blue');suggested.tags.color=['blue'];rejected.tags.color=['blue'];rejected.tagging=decideTag(rejected.tagging,'color.blue','rejected');for(const s of [suggested,rejected])assert.deepEqual(searchableSegmentIds(s),[]);assert.equal(rankImageSegments(filterSegments([clip([suggested,rejected])],'',[]),query()).length,0);});
await test('Legacy suggested/rejected are excluded; accepted review overrides legacy',()=>{for(const status of ['suggested','rejected'] as const){const s={...segment(status),tags:undefined,tagIds:['color.blue'],effects:['blue'],legacyStatus:{'color.blue':status}};assert.deepEqual(searchableSegmentIds(s),[]);s.tagging=decideTag(emptyTagging(),'color.blue','accepted');assert.deepEqual(searchableSegmentIds(s),['color.blue']);}});
await test('Parent review snapshot correctly filters old legacy tagIds',()=>{const s={...segment('legacy'),tags:undefined,tagIds:['color.blue'],effects:['blue']};const c=clip([s],'color.blue');c.tagging=decideTag(c.tagging,'color.blue','rejected');assert.equal(rankImageSegments(filterSegments([c],'',[]),query()).length,0);});
await test('Unambiguous manual aliases match without borrowing a parent',()=>{const s={...segment('manual'),tags:{color:['푸른색'],shot:['클로즈업'],effect:[]}};assert(searchableSegmentIds(s).includes('color.blue'));assert(searchableSegmentIds(s).includes('shot_type.close_up'));assert.equal(rankImageSegments(filterSegments([clip([s])],'',[]),query()).length,1);});
await test('Allowlist excludes temporal, camera motion and production IDs',()=>{assert(imageTags.length>0);for(const t of imageTags){assert(t.observable);assert(!['camera_motion','motion_style','production_technique','generation_method'].includes(t.namespace));}for(const id of ['camera_motion.pan','motion_style.slow_motion','production_technique.rotoscoping','generation_method.diffusion','unknown.tag'])assert.throws(()=>parseImageQuery(JSON.stringify(body(id))));});
await test('Ranking combines own exact matches and preserves input immutability',()=>{const c=clip([segment('blue','color.blue'),{...segment('both','color.blue'),tagging:aiTagging([{tagId:'color.blue',aiScore:.96,evidenceMs:[1000]},{tagId:'shot_type.close_up',aiScore:.96,evidenceMs:[1000]}],5)}]);const items=filterSegments([c],'',[]),snapshot=JSON.stringify(items);const q=parseImageQuery(JSON.stringify({...body(),tags:[...body().tags,{tagId:'shot_type.close_up',aiScore:.9,reason:'가까운 구도'}]}));const ranked=rankImageSegments(items,q);assert.equal(ranked[0].segment.id,'both');assert(ranked[0].imageMatch!.score>ranked[1].imageMatch!.score);assert.equal(JSON.stringify(items),snapshot);});
await test('Explicit static appearance pairs match across namespaces in both directions at .8 weight',()=>{const pairs=[['visual_style.rgb_split','transformation.rgb_split'],['visual_style.chromatic_aberration','transformation.chromatic_aberration'],['visual_style.outline','transformation.outline'],['visual_style.threshold','transformation.threshold'],['visual_style.monochrome','color.monochrome']];for(const pair of pairs)for(const [stored,asked] of [pair,[...pair].reverse()]){const s=segment('appearance',stored);const items=filterSegments([clip([s])],'',[]);const q=parseImageQuery(JSON.stringify(body(asked,1)));const result=rankImageSegments(items,q);assert.equal(result.length,1,stored+' → '+asked);assert.equal(result[0].imageMatch!.score,.8);assert(result[0].imageMatch!.labels[0].endsWith(' 유사'));assert.deepEqual(searchableSegmentIds(s),[stored],'namespace remains intact');}});
await test('Equivalent query duplicates contribute only max score once',()=>{const items=filterSegments([clip([segment('rgb','visual_style.rgb_split')])],'',[]);const make=(tags:any[])=>parseImageQuery(JSON.stringify({...body(),tags}));const a=body('visual_style.rgb_split',.95).tags[0],b=body('transformation.rgb_split',.99).tags[0];const only=rankImageSegments(items,make([a]))[0];const both=rankImageSegments(items,make([a,b]))[0];const reversed=rankImageSegments(items,make([b,a]))[0];assert.equal(both.imageMatch!.score,only.imageMatch!.score);assert.equal(reversed.imageMatch!.score,only.imageMatch!.score);assert.equal(both.imageMatch!.labels.length,1);const highest=rankImageSegments(items,make([{...a,aiScore:.6},b]))[0];assert.equal(highest.imageMatch!.score,.99*.8);});
await test('Ambiguous manual RGB Split alias is usable only as one explicit appearance group',()=>{const s={...segment('manual-rgb'),tags:{color:[],shot:[],effect:['RGB Split']}};const ids=searchableSegmentIds(s);assert.equal(ids.length,1);assert(['visual_style.rgb_split','transformation.rgb_split'].includes(ids[0]));for(const asked of ['visual_style.rgb_split','transformation.rgb_split'])assert.equal(rankImageSegments(filterSegments([clip([s])],'',[]),parseImageQuery(JSON.stringify(body(asked)))).length,1);});
await test('Manual equivalent aliases do not bypass rejected or suggested canonical/legacy decisions',()=>{for(const id of ['visual_style.rgb_split','transformation.rgb_split'])for(const status of ['rejected','suggested'] as const){const s={...segment('manual-rgb'),tags:{color:[],shot:[],effect:['RGB Split']},legacyStatus:{[id]:status}};assert.deepEqual(searchableSegmentIds(s),[]);for(const asked of ['visual_style.rgb_split','transformation.rgb_split'])assert.equal(rankImageSegments(filterSegments([clip([s])],'',[]),parseImageQuery(JSON.stringify(body(asked)))).length,0);const ai=aiTagging([{tagId:id,aiScore:.7,evidenceMs:[1000]}],5);s.tagging=status==='rejected'?decideTag(ai,id,'rejected'):ai;assert.deepEqual(searchableSegmentIds(s),[]);}});
await test('REGRESSION: an explicit rejection is not bypassed by a different accepted equivalent ID',()=>{const s=segment('rejected-specific','visual_style.rgb_split');s.tagging=decideTag(s.tagging,'transformation.rgb_split','rejected');const items=filterSegments([clip([s])],'',[]);assert.equal(rankImageSegments(items,parseImageQuery(JSON.stringify(body('transformation.rgb_split')))).length,0);assert.equal(rankImageSegments(items,parseImageQuery(JSON.stringify(body('visual_style.rgb_split')))).length,1);});
await test('Malformed, unreadable, empty, low-confidence and excessive image results reject',()=>{for(const v of [null,{}, {...body(),imageReadable:false},{...body(),summary:'x'.repeat(401)},{...body(),tags:[]},body('color.blue',.59),body('color.blue',1.01),{...body(),tags:[{...body().tags[0],reason:' '}]},{...body(),tags:Array.from({length:13},()=>body().tags[0])}])assert.throws(()=>parseImageQuery(JSON.stringify(v)));assert.throws(()=>parseImageQuery('{bad'));});
await test('Duplicate tags are deduplicated and threshold scores remain finite',()=>{const q=parseImageQuery(JSON.stringify({...body(),tags:[body().tags[0],body().tags[0],{...body().tags[0],tagId:'shot_type.close_up',aiScore:.6}]}));assert.equal(q.tags.length,2);assert.equal(q.tags[1].aiScore,.6);});
await test('Search image input rejects URL, SVG, malformed data and excessive length',()=>{assert.equal(parseSearchImage({image:fixtureImage}),fixtureImage);for(const image of [undefined,'https://example.org/pic.jpg','data:image/svg+xml;base64,AAA','data:image/png;base64,AAA','data:image/jpeg;base64,/9j/!','data:image/jpeg;base64,/9j/','data:image/jpeg;base64,/9j/'+'A'.repeat(2100000)])assert.throws(()=>parseSearchImage({image}));});
await test('Both provider response parsers enforce completion and ignore reasoning parts',()=>{const text=JSON.stringify(body());assert.equal(parseImageResponse('openai',{status:'completed',output:[{type:'message',content:[{type:'output_text',text}]}]}).provider,'openai');assert.equal(parseImageResponse('gemini',{candidates:[{finishReason:'STOP',content:{parts:[{thought:true,text:'invalid hidden reasoning'},{text}]}}]}).provider,'gemini');for(const [provider,data] of [['openai',{status:'incomplete',output:[]}],['gemini',{candidates:[{finishReason:'MAX_TOKENS'}]}]] as const)assert.throws(()=>parseImageResponse(provider,data));assert.equal((imageRequest('openai',fixtureImage) as any).store,false);assert.equal((imageRequest('gemini',fixtureImage) as any).contents[0].parts[0].inlineData.mimeType,'image/jpeg');});
env.DB={prepare(){return{async all(){return{results:[]};},bind(){return{async first(){return null;}};}};}};
let providerCalls=0,mode='success';const originalFetch=globalThis.fetch;
globalThis.fetch=async(_url:any,init:any)=>{providerCalls++;if(init.signal.aborted)throw new DOMException('Aborted','AbortError');if(mode==='401'||mode==='429'||mode==='500')return new Response('provider error',{status:Number(mode)});if(mode==='malformed')return Response.json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:'bad json'}]}]});return Response.json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(body())}]}]});};
env.OPENAI_API_KEY='fixture-not-a-real-key';delete env.GEMINI_API_KEY;
async function call(raw:string,headers:Record<string,string>={},signal?:AbortSignal){return POST(new Request('http://localhost/api/ai/image-query',{method:'POST',headers,body:raw,signal}));}
try{
await test('API success uses configured provider without storing request image',async()=>{providerCalls=0;mode='success';const res=await call(JSON.stringify({image:fixtureImage}));assert.equal(res.status,200);const data:any=await res.json();assert.equal(data.provider,'openai');assert.equal(data.tags[0].tagId,'color.blue');assert.equal(providerCalls,1);assert(!('image' in data));assert.equal(res.headers.get('cache-control'),'no-store');});
await test('API rejects malformed JSON and unsupported image before any provider call',async()=>{providerCalls=0;for(const raw of ['{bad','null','[]',JSON.stringify({image:'data:image/png;base64,AAAA'})]){const res=await call(raw);assert(res.status>=400);assert(res.status<500);}assert.equal(providerCalls,0);});
await test('API rejects foreign origin and advertised/streamed oversized bodies',async()=>{providerCalls=0;assert.equal((await call(JSON.stringify({image:fixtureImage}),{origin:'https://evil.invalid'})).status,403);assert.equal((await call('{}',{'content-length':String(IMAGE_BODY_LIMIT+1)})).status,413);assert((await call(' '.repeat(IMAGE_BODY_LIMIT+1))).status>=400);assert.equal(providerCalls,0);});
await test('Unconfigured AI returns 409 without a provider request',async()=>{providerCalls=0;delete env.OPENAI_API_KEY;assert.equal((await call(JSON.stringify({image:fixtureImage}))).status,409);assert.equal(providerCalls,0);env.OPENAI_API_KEY='fixture-not-a-real-key';});
await test('Provider auth/rate/server errors and malformed result are user-visible errors',async()=>{for(const m of ['401','429','500','malformed']){mode=m;const res=await call(JSON.stringify({image:fixtureImage}));assert.equal(res.status,422);const data:any=await res.json();assert.equal(typeof data.error,'string');assert(data.error.length>0);assert(!JSON.stringify(data).includes('fixture-not-a-real-key'));}});
await test('Already-aborted request cannot return a successful search result',async()=>{mode='success';const abort=new AbortController();abort.abort();const res=await call(JSON.stringify({image:fixtureImage}),{},abort.signal);assert.equal(res.status,422);const data:any=await res.json();assert(data.error.includes('취소'));});
}finally{globalThis.fetch=originalFetch;delete env.OPENAI_API_KEY;}
console.log(JSON.stringify({passed,failed}));if(failed)process.exitCode=1;
