import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {env} from './mock-cloudflare';
import {submit,workerAction,changeJob,listJobs,canonicalSource,internal,localSegments} from '../../apps/web/lib/jobs/server';
import {aiTagging,decideTag} from '../../apps/web/lib/tagging';
import {serialize} from '../../apps/web/lib/server';
const sql=new DatabaseSync(':memory:');
for(const name of readdirSync('apps/web/drizzle').filter(n=>n.endsWith('.sql')).sort())sql.exec(readFileSync('apps/web/drizzle/'+name,'utf8'));
function statement(query:string,values:unknown[]=[]):any{return{query,values,bind(...args:unknown[]){return statement(query,args);},async first(){return sql.prepare(query).get(...values as any[])||null;},async all(){return{results:sql.prepare(query).all(...values as any[])};},async run(){return{meta:{changes:Number(sql.prepare(query).run(...values as any[]).changes)}};}};}
env.DB={prepare:statement,async batch(statements:any[]){sql.exec('BEGIN');try{const results=[];for(const s of statements)results.push({meta:{changes:Number(sql.prepare(s.query).run(...s.values).changes)}});sql.exec('COMMIT');return results;}catch(e){sql.exec('ROLLBACK');throw e;}}};
env.CUTNOTE_PC_TOKEN='test-worker-capability';
const id=crypto.randomUUID(),source='https://www.youtube.com/shorts/-hzFMRT-bbU?si=tracking';
const data=async(r:Response)=>{assert(r.ok,await r.clone().text());return r.json();};
assert.equal(canonicalSource(source),'https://www.youtube.com/watch?v=-hzFMRT-bbU');
assert.equal(canonicalSource('https://www.instagram.com/reels/DcwzP1IuUD9/'),'https://www.instagram.com/reel/DcwzP1IuUD9/');
for(const bad of ['file:///a','https://youtube.com.evil.test/watch?v=-hzFMRT-bbU','https://user@youtube.com/watch?v=-hzFMRT-bbU','https://127.0.0.1/','https://youtube.com/playlist?list=abc'])assert.throws(()=>canonicalSource(bad));
assert(!internal(new Request('http://localhost/api/internal/jobs')));
const [a,b]=await Promise.all([submit({requestId:id,sourceUrl:source}),submit({requestId:id,sourceUrl:source})]);
assert(a.ok&&b.ok);assert.equal((sql.prepare('SELECT count(*) n FROM clips').get() as any).n,1);assert.equal((await listJobs()).length,1);
assert.equal((await submit({requestId:id,sourceUrl:'https://youtu.be/abcdefghijk'})).status,409);
const claimed=(await data(await workerAction({action:'claim'}))).job;assert.equal(claimed.id,id);assert.equal((await data(await workerAction({action:'claim'}))).job,null);
assert.equal((await workerAction({action:'progress',id,token:'wrong',phase:'analyze'})).status,409);
const identity={id,token:claimed.lease_token};
const asset={root:crypto.randomUUID(),directory:id,video:'video.mp4',poster:'poster.jpg',mime:'video/mp4',size:40*1024**2,duration:10};
const attached=await data(await workerAction({action:'attach',...identity,asset,revision:0}));assert.equal(attached.revision,1);
const clip=sql.prepare('SELECT * FROM clips WHERE id=?').get(id) as any;assert(serialize(clip).localVideo);assert.equal(serialize(clip).videoUrl,'/api/media/'+id);
await data(await workerAction({action:'fail',...identity,code:'analysis_failed'}));assert.equal((await listJobs())[0].errorCode,'analysis_failed');assert(serialize(clip).videoUrl);
await data(await changeJob(id,'retry'));const retry=(await data(await workerAction({action:'claim'}))).job;assert(retry.asset);assert.equal(retry.attempt,2);
await changeJob(id,'cancel');assert.equal((await data(await workerAction({action:'heartbeat',id,token:retry.lease_token}))).cancel,true);
await data(await workerAction({action:'fail',id,token:retry.lease_token,code:'cancelled'}));assert.equal((await listJobs())[0].state,'cancelled');
await changeJob(id,'retry');const restart=(await data(await workerAction({action:'claim'}))).job;sql.prepare('UPDATE pc_jobs SET lease_until=0').run();assert.equal((await listJobs())[0].state,'interrupted');assert.equal((await workerAction({action:'progress',id,token:restart.lease_token,phase:'analyze'})).status,409);
sql.prepare('DELETE FROM clips WHERE id=?').run(id);assert.equal((await changeJob(id,'retry')).status,404);await submit({requestId:id,sourceUrl:source});assert.equal((sql.prepare('SELECT count(*) n FROM clips').get() as any).n,0);
console.log('PASS: PC jobs canonicalization, atomic duplicate receipt, leases, large local asset, separated failure, cancel, restart, deletion tombstone; no network calls.');
const completedId=crypto.randomUUID();
await data(await submit({requestId:completedId,sourceUrl:source,fields:{title:'manual title',notes:'manual memo',tags:{color:['custom'],shot:[],effect:[]}}}));
const next=(await data(await workerAction({action:'claim'}))).job;
const nextIdentity={id:next.id,token:next.lease_token};
await data(await workerAction({action:'attach',...nextIdentity,asset:{...asset,directory:completedId},revision:0}));
const segment={id:'segment-a',title:'my segment',startSeconds:1,endSeconds:3,effects:[],note:'my memo',tags:{color:['custom'],shot:[],effect:[]},tagging:decideTag(aiTagging([{tagId:'color.blue',aiScore:.96,evidenceMs:[1500]}],10),'color.blue','rejected')};
sql.prepare('UPDATE clips SET segments=?,favorite_segments=? WHERE id=?').run(JSON.stringify([segment]),JSON.stringify([segment.id]),completedId);
const report={engine:'openai-frames-v1',basis:'full-duration-frames',model:'gpt-6-sol',frameCount:20,durationSeconds:10,analyzedAt:new Date().toISOString(),suggestedTags:{color:[],shot:[],effect:[]},notes:[],segments:[{...segment,title:'AI title',tagging:aiTagging([{tagId:'color.blue',aiScore:.99,evidenceMs:[1700]}],10)}]};
const result={title:'AI title',memo:'AI memo',report};
assert.equal((await workerAction({action:'complete',...nextIdentity,revision:0,result})).status,409);
assert.equal((sql.prepare('SELECT state FROM pc_jobs WHERE id=?').get(completedId) as any).state,'running');
await data(await workerAction({action:'complete',...nextIdentity,revision:1,result}));
assert.equal((sql.prepare('SELECT state FROM pc_jobs WHERE id=?').get(completedId) as any).state,'completed');
let saved=serialize(sql.prepare('SELECT * FROM clips WHERE id=?').get(completedId) as any);
assert.equal(saved.title,'manual title');assert.equal(saved.notes,'manual memo');assert.deepEqual(saved.tags.color,['custom']);assert.deepEqual(saved.favoriteSegmentIds,[segment.id]);assert.equal(saved.segments![0].tagging!.assignments[0].status,'rejected');
const retagId=crypto.randomUUID(),targets=[{id:segment.id,startSeconds:1,endSeconds:3}];
await data(await submit({requestId:retagId,kind:'retag',clipId:completedId,segmentTargets:targets}));
let task=(await data(await workerAction({action:'claim'}))).job;
await data(await workerAction({action:'complete',id:task.id,token:task.lease_token,revision:task.revision,result}));
// A replay after commit must not conflict merely because the clip revision grew.
assert.equal((await submit({requestId:retagId,kind:'retag',clipId:completedId,segmentTargets:targets})).status,200);
saved=serialize(sql.prepare('SELECT * FROM clips WHERE id=?').get(completedId) as any);assert.equal(saved.segments![0].title,'my segment');assert.deepEqual(saved.favoriteSegmentIds,[segment.id]);
const exportId=crypto.randomUUID();await data(await submit({requestId:exportId,kind:'export',clipId:completedId,segmentTargets:targets}));task=(await data(await workerAction({action:'claim'}))).job;
await data(await workerAction({action:'complete',id:task.id,token:task.lease_token,revision:task.revision,result:{...task.asset,video:'export-'+exportId+'.mp4',size:1000,duration:2,width:640,height:360}}));
const local=await localSegments(sql.prepare('SELECT * FROM clips WHERE id=?').get(completedId) as any);assert(local[0].file?.url.includes(exportId)===false);assert.equal(local[0].file?.size,1000);
sql.prepare('UPDATE clips SET segments=? WHERE id=?').run(JSON.stringify([{...segment,endSeconds:4}]),completedId);assert.equal((await localSegments(sql.prepare('SELECT * FROM clips WHERE id=?').get(completedId) as any))[0].file,null);
console.log('PASS: actual SQL commit/CAS, metadata/rejected tags/favorites preservation, retag replay, local export and stale-range invalidation.');
