import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {env} from './mock-cloudflare';
import {parseIntent,intentKey,confirmedEffectIds,recommendationItems,recommendSegments,segmentSignature,seedIntent,localEffectIntent,presetIntent} from '../../apps/web/features/discovery/recommendations';
import {emptyTagging,decideTag,aiTagging} from '../../apps/web/lib/tagging';
import {parseEffectResponse} from '../../apps/web/lib/ai/effect-query';
import {POST as search} from '../../apps/web/app/api/ai/effect-query/route';
import {GET,POST} from '../../apps/web/app/api/recommendations/feedback/route';
import {serialize} from '../../apps/web/lib/server';

const blank=()=>({color:[],shot:[],effect:[]});
const tagging=(...ids:string[])=>ids.reduce((t,id)=>decideTag(t,id,'accepted'),emptyTagging());
const seg=(id:string,...ids:string[]):any=>({id,title:id,startSeconds:0,endSeconds:5,note:'',effects:[],tags:blank(),tagging:tagging(...ids)});
const clip=(segments:any[],...ids:string[]):any=>({id:'fixture',title:'parent glow',notes:'parent shake',sourceUrl:'https://example.org/v',videoUrl:null,posterUrl:null,tags:{color:[],shot:[],effect:['glow']},tagging:tagging(...ids),segments,createdAt:'2026-09-29'});
const intent=(...groups:string[][])=>parseIntent({summary:'검색 조건',groups:groups.map((tagIds,i)=>({label:'조건 '+i,tagIds}))});
const glow=intent(['transformation.glow']),multi=intent(['transformation.glow','transformation.bloom'],['motion_style.shake']);
const items=(...segments:any[])=>recommendationItems([clip(segments)]);
const rank=(segments:any[],i=glow,feedback:any[]=[])=>recommendSegments(items(...segments),i,feedback);
let passed=0,failed=0;
async function test(name:string,fn:()=>void|Promise<void>){try{await fn();passed++;console.log('PASS',name);}catch(e){failed++;console.error('FAIL',name,':',(e as Error).message);}}
await test('Required groups use AND; alternatives within each group use OR',()=>{const r=rank([seg('all','transformation.bloom','motion_style.shake'),seg('partial','transformation.glow'),seg('other','color.blue')],multi);assert.deepEqual(r.map(x=>[x.segment.id,x.kind]),[['all','exact'],['partial','similar']]);});
await test('Exact parent concepts accept descendants but not siblings or ancestor-only tags',()=>{const parent=intent(['visual_style.glitch']);assert.equal(rank([seg('child','visual_style.digital_glitch')],parent)[0].kind,'exact');const child=intent(['visual_style.digital_glitch']);assert.equal(rank([seg('parent','visual_style.glitch')],child)[0].kind,'similar');});
await test('Similar families remain similar; unrelated segments do not appear',()=>{assert.equal(rank([seg('bloom','transformation.bloom')])[0].kind,'similar');assert.equal(rank([seg('unrelated','geometry_pattern.checkerboard')]).length,0);});
await test('Parent tags, parent title and neighboring intervals cannot become segment evidence',()=>{const c=clip([seg('empty'),seg('match','transformation.glow')],'transformation.glow');assert.deepEqual(recommendSegments(recommendationItems([c]),glow).map(r=>r.segment.id),['match']);});
await test('Only accepted assignments count, even when stale free labels remain',()=>{for(const status of ['suggested','rejected'] as const){const s=seg(status);s.tagging=status==='suggested'?aiTagging([{tagId:'transformation.glow',aiScore:.7,evidenceMs:[1000]}],5):decideTag(emptyTagging(),'transformation.glow','rejected');s.tags.effect=['glow'];assert.deepEqual(confirmedEffectIds(s),[]);assert.equal(rank([s]).length,0);}});
await test('Legacy decisions remain respected; independent user acceptance overrides old state',()=>{for(const status of ['suggested','rejected'] as const){const s={...seg('legacy'),tagging:undefined,tags:undefined,tagIds:['transformation.glow'],legacyStatus:{'transformation.glow':status}};assert.equal(rank([s]).length,0);s.tagging=tagging('transformation.glow');assert.equal(rank([s])[0].kind,'exact');}});
await test('Legacy tagIds inherit only their own status snapshot, not unrelated parent IDs',()=>{const c=clip([{...seg('legacy'),tagging:undefined,tags:undefined,tagIds:['transformation.glow']}],'transformation.glow');c.tagging=decideTag(c.tagging,'transformation.glow','rejected');assert.equal(recommendSegments(recommendationItems([c]),glow).length,0);});
await test('Unambiguous manual tag can match; ambiguous or unknown names do not invent canonical IDs',()=>{const s=seg('manual');s.tagging=undefined;s.tags.effect=['glow'];assert(confirmedEffectIds(s).includes('transformation.glow'));s.tags.effect=['RGB Split','custom-fx'];assert.deepEqual(confirmedEffectIds(s),[]);});
await test('Explicit rejected/suggested query IDs cannot match through a related accepted family',()=>{for(const state of ['rejected','suggested'] as const){const s=seg('blocked','transformation.bloom');s.tagging=state==='rejected'?decideTag(s.tagging,'transformation.glow','rejected'):{...s.tagging,assignments:[...s.tagging.assignments,...aiTagging([{tagId:'transformation.glow',aiScore:.7,evidenceMs:[1000]}],5).assignments]};assert.equal(rank([s]).length,0);}});
await test('Feedback changes ordering only within the original exact/similar bucket',()=>{const list=items(seg('exact-a','transformation.glow'),seg('exact-b','transformation.glow'),seg('similar','transformation.bloom'));const feedback=list.map(i=>({clipId:i.clip.id,segmentId:i.segment.id,signature:segmentSignature(i),value:i.segment.id==='similar'?'match':i.segment.id==='exact-a'?'partial':null}));const r=recommendSegments(list,glow,feedback as any);assert.deepEqual(r.map(x=>[x.segment.id,x.kind]),[['exact-b','exact'],['exact-a','exact'],['similar','similar']]);});
await test('Irrelevant remains available for UI hide/undo without changing tags or buckets',()=>{const list=items(seg('a','transformation.glow')),before=JSON.stringify(list);const f={clipId:'fixture',segmentId:'a',signature:segmentSignature(list[0]),value:'irrelevant' as const};const r=recommendSegments(list,glow,[f]);assert.equal(r[0].feedback,'irrelevant');assert.equal(r[0].kind,'exact');assert.equal(JSON.stringify(list),before);assert.equal(recommendSegments(list,glow,[{...f,value:null}])[0].feedback,null);});
await test('Range, confirmed tag and source changes invalidate feedback; memo/title edits retain it',()=>{const original=items(seg('a','transformation.glow'))[0],signature=segmentSignature(original),f={clipId:'fixture',segmentId:'a',signature,value:'irrelevant' as const};for(const change of [(x:any)=>x.segment.endSeconds=6,(x:any)=>x.segment.tagging=tagging('transformation.glow','color.blue'),(x:any)=>x.clip.sourceUrl='https://example.org/new',(x:any)=>x.clip.videoUrl='/api/media/new']){const x=structuredClone(original);change(x);assert.notEqual(segmentSignature(x),signature);assert.equal(recommendSegments([x],glow,[f])[0].feedback,null);}const x=structuredClone(original);x.segment.title='changed';x.segment.note='new';assert.equal(segmentSignature(x),signature);assert.equal(recommendSegments([x],glow,[f])[0].feedback,'irrelevant');});
await test('Similar seed excludes its own interval and uses at most five confirmed conditions',()=>{const s=seg('seed','transformation.glow','color.blue','motion_style.shake','texture.grainy','visual_style.glitch','geometry_pattern.checkerboard');const list=items(s,seg('other','transformation.glow'));const i=seedIntent(list[0]);assert.equal(i.groups.length,5);assert.equal(recommendSegments(list,i,[],'fixture/seed').some(x=>x.segment.id==='seed'),false);});
await test('Context keys ignore labels, group order and duplicate equivalent groups, but preserve AND/OR semantics',()=>{assert.equal(intentKey(multi),intentKey(parseIntent({summary:'different',groups:[{label:'shake',tagIds:['motion_style.shake']},{label:'light',tagIds:['transformation.bloom','transformation.glow','transformation.glow']},{label:'duplicate',tagIds:['motion_style.shake']}]})));assert.notEqual(intentKey(intent(['transformation.glow','transformation.bloom'])),intentKey(intent(['transformation.glow'],['transformation.bloom'])));});
await test('Intent bounds, allowlist and preset/local fallback behavior are validated',()=>{for(const v of [null,{},[],{summary:'x',groups:[{label:'x',tagIds:['unknown']} ]},{summary:'x',groups:[{label:'x',tagIds:['subject.person']} ]},{summary:'x',groups:Array.from({length:6},()=>({label:'x',tagIds:['transformation.glow']}))},{summary:'x'.repeat(301),groups:[]}])assert.throws(()=>parseIntent(v));for(const name of ['glow','dynamic','dreamy','strong'])assert(parseIntent(presetIntent(name)).groups.length);assert.equal(localEffectIntent('멋있는 효과').groups.length,0);assert.equal(localEffectIntent('화면이 흔들리면서 확대').groups.length,2);});
await test('Specific Digital Glitch alias retains the child concept rather than broad Glitch',()=>{for(const name of ['digital glitch','digital_glitch','visual_style.digital_glitch'])assert.deepEqual(localEffectIntent(name).groups.map(g=>g.tagIds),[['visual_style.digital_glitch']]);});
await test('Unsupported negative, direction and speed phrases do not silently become opposite intent',()=>{for(const q of ['글리치 없이','흔들림 제외','확대 말고','천천히 줌','slow zoom','zoom out','화면이 멀어지는 줌'])assert.equal(localEffectIntent(q).groups.length,0,q);assert(localEffectIntent('zoom out').groups.length===0||localEffectIntent('zoom out').groups[0].tagIds.every(id=>!id.includes('crash_zoom')));});
await test('Actual zoom outranks dreamy-only for glow AND zoom even with positive mood feedback',()=>{const list=items(seg('dreamy','visual_style.dreamy'),seg('zoom','motion_style.zoom'));const feedback=[{clipId:'fixture',segmentId:'dreamy',signature:segmentSignature(list[0]),value:'match' as const},{clipId:'fixture',segmentId:'zoom',signature:segmentSignature(list[1]),value:'partial' as const}];const r=recommendSegments(list,intent(['transformation.glow'],['motion_style.zoom']),feedback);assert.deepEqual(r.map(x=>[x.segment.id,x.kind]),[['zoom','similar'],['dreamy','similar']]);assert.equal(r[1].weights[0],0);assert(r[1].reason.includes('분위기'));});
await test('Actual glitch outranks grain-only for glitch AND grainy even with positive texture feedback',()=>{const list=items(seg('grain','texture.grainy'),seg('glitch','visual_style.glitch'));const feedback=[{clipId:'fixture',segmentId:'grain',signature:segmentSignature(list[0]),value:'match' as const},{clipId:'fixture',segmentId:'glitch',signature:segmentSignature(list[1]),value:'partial' as const}];assert.deepEqual(recommendSegments(list,intent(['visual_style.glitch'],['texture.grainy']),feedback).map(x=>x.segment.id),['glitch','grain']);});
await test('Provider result parsers reject incomplete/malformed results and ignore thought text',()=>{const text=JSON.stringify(multi);assert.equal(parseEffectResponse('gemini',{candidates:[{finishReason:'STOP',content:{parts:[{thought:true,text:'bad'},{text}]}}]}).groups.length,2);assert.equal(parseEffectResponse('openai',{status:'completed',output:[{type:'message',content:[{type:'output_text',text}]}]}).groups.length,2);for(const [p,v] of [['gemini',{candidates:[{finishReason:'MAX_TOKENS'}]}],['openai',{status:'incomplete',output:[]}],['openai',{status:'completed',output:[{type:'message',content:[{type:'output_text',text:'bad'}]}]}]] as const)assert.throws(()=>parseEffectResponse(p,v));});

const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');for(const file of readdirSync('apps/web/drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync('apps/web/drizzle/'+file,'utf8'));
let failWrite=false,afterRead:undefined|(()=>void);
env.DB={prepare(query:string){const bound=(values:any[]=[])=>({async first(){const row=sql.prepare(query).get(...values)||null;if(query==='SELECT * FROM clips WHERE id = ?'&&afterRead){const next=afterRead;afterRead=undefined;next();}return row;},async all(){return{results:sql.prepare(query).all(...values)};},async run(){if(failWrite)throw new Error('fixture storage unavailable');return{meta:{changes:Number(sql.prepare(query).run(...values).changes)}};}});return{...bound(),bind(...values:any[]){return bound(values);}};}};
function reset(){failWrite=false;afterRead=undefined;sql.exec('DELETE FROM recommendation_feedback; DELETE FROM clips; DELETE FROM ai_settings');sql.prepare('INSERT INTO clips(id,title,source_url,tags,notes,created_at,segments,tagging) VALUES(?,?,?,?,?,?,?,?)').run('fixture','parent','https://example.org/v',JSON.stringify(blank()),'original memo','2026-09-29',JSON.stringify([seg('a','transformation.glow'),seg('b','transformation.bloom')]),JSON.stringify(emptyTagging()));}
const stored=()=>serialize(sql.prepare('SELECT * FROM clips WHERE id=?').get('fixture') as any);
const payload=(value:any='match',i=glow,id='a')=>{const item=recommendationItems([stored()]).find(x=>x.segment.id===id)!;return{intent:i,clipId:'fixture',segmentId:id,signature:segmentSignature(item),value};};
const callPost=(body:any,headers:Record<string,string>={})=>POST(new Request('http://localhost/api/recommendations/feedback',{method:'POST',headers,body:typeof body==='string'?body:JSON.stringify(body)}));
const get=(context=intentKey(glow),headers:Record<string,string>={})=>GET(new Request('http://localhost/api/recommendations/feedback?context='+encodeURIComponent(context),{headers}));
await test('Feedback persists in D1 per canonical context and never mutates clip metadata',async()=>{reset();const before=JSON.stringify(stored());assert.equal((await callPost(payload())).status,200);assert.equal((await get()).status,200);assert.equal((await(await get()).json() as any).feedback[0].value,'match');assert.equal((await(await get(intentKey(multi))).json() as any).feedback.length,0);assert.equal(JSON.stringify(stored()),before);});
await test('Irrelevant feedback survives reload and undo removes it from GET results',async()=>{reset();assert.equal((await callPost(payload('irrelevant'))).status,200);assert.equal((await(await get()).json() as any).feedback[0].value,'irrelevant');assert.equal((await callPost(payload(null))).status,200);assert.deepEqual((await(await get()).json() as any).feedback,[]);assert.equal(sql.prepare('SELECT count(*) AS n FROM recommendation_feedback').get()!.n,1);});
await test('Concurrent feedback for distinct segments and contexts does not overwrite unrelated records',async()=>{reset();const r=await Promise.all([callPost(payload('match',glow,'a')),callPost(payload('partial',glow,'b')),callPost(payload('irrelevant',multi,'a'))]);assert(r.every(x=>x.status===200));assert.equal((await(await get()).json() as any).feedback.length,2);assert.equal((await(await get(intentKey(multi))).json() as any).feedback.length,1);});
await test('Stale source/range/tag signatures reject writes with 409',async()=>{reset();const old=payload();sql.prepare('UPDATE clips SET source_url=? WHERE id=?').run('https://example.org/new','fixture');assert.equal((await callPost(old)).status,409);assert.equal(sql.prepare('SELECT count(*) AS n FROM recommendation_feedback').get()!.n,0);});
await test('Source changes during a feedback request leave old vote inapplicable',async()=>{reset();const old=payload();afterRead=()=>sql.prepare('UPDATE clips SET source_url=? WHERE id=?').run('https://example.org/new','fixture');const res=await callPost(old);assert([200,409].includes(res.status));const feedback=(await(await get()).json() as any).feedback;assert.equal(recommendSegments(recommendationItems([stored()]),glow,feedback)[0].feedback,null);});
await test('Unknown clip and segment receive 404; rejected writes do not create records',async()=>{reset();assert.equal((await callPost({...payload(),clipId:'missing'})).status,404);assert.equal((await callPost({...payload(),segmentId:'missing'})).status,404);assert.equal(sql.prepare('SELECT count(*) AS n FROM recommendation_feedback').get()!.n,0);});
await test('Feedback POST validates malformed intent as a client error',async()=>{reset();for(const bad of ['null','[]','{}',JSON.stringify({...payload(),intent:{summary:'bad',groups:[{label:'x',tagIds:['unknown']}]}})])assert.equal((await callPost(bad)).status,400,bad);});
await test('Feedback POST rejects malformed values and oversized streamed input without writes',async()=>{reset();for(const bad of ['{bad',' '.repeat(30001),{...payload(),value:'wrong'},{...payload(),clipId:'x'.repeat(65)},{...payload(),segmentId:'x'.repeat(65)},{...payload(),signature:'x'.repeat(20001)}]){const response=await callPost(bad);assert.equal(response.status,400);}assert.equal(sql.prepare('SELECT count(*) AS n FROM recommendation_feedback').get()!.n,0);});
await test('Feedback GET validates bounded canonical context and malformed input',async()=>{reset();for(const context of ['','null','{}','["bad"]',' '.repeat(5001),JSON.stringify(Array.from({length:6},()=>['transformation.glow']))])assert.equal((await get(context)).status,400);});
await test('Foreign-origin feedback POST is rejected before any write',async()=>{reset();assert.equal((await callPost(payload(),{origin:'https://evil.invalid'})).status,403);assert.equal(sql.prepare('SELECT count(*) AS n FROM recommendation_feedback').get()!.n,0);});
await test('Foreign-origin feedback GET is rejected before reading stored votes',async()=>{reset();await callPost(payload());assert.equal((await get(intentKey(glow),{origin:'https://evil.invalid'})).status,403);});
await test('Feedback database failure returns error rather than successful vote',async()=>{reset();failWrite=true;const response=await callPost(payload());assert.equal(response.status,500);assert.equal(sql.prepare('SELECT count(*) AS n FROM recommendation_feedback').get()!.n,0);failWrite=false;});
await test('Deleting a clip cascades saved recommendation feedback',async()=>{reset();await callPost(payload());sql.prepare('DELETE FROM clips WHERE id=?').run('fixture');assert.equal(sql.prepare('SELECT count(*) AS n FROM recommendation_feedback').get()!.n,0);});

let calls=0,mode='success';const originalFetch=globalThis.fetch;
globalThis.fetch=async(_url:any,init:any)=>{calls++;if(init.signal.aborted)throw new DOMException('Aborted','AbortError');if(['401','429','500'].includes(mode))return new Response('fixture provider error',{status:Number(mode)});return Response.json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:mode==='bad'?'bad json':JSON.stringify(multi)}]}]});};
const searchCall=(raw:any,headers:Record<string,string>={},signal?:AbortSignal)=>search(new Request('http://localhost/api/ai/effect-query',{method:'POST',headers,body:typeof raw==='string'?raw:JSON.stringify(raw),signal}));
try{
await test('Unconfigured AI uses local dictionary with no paid request',async()=>{reset();delete env.OPENAI_API_KEY;delete env.GEMINI_API_KEY;calls=0;const r=await searchCall({query:'화면이 흔들리면서 확대'});assert.equal(r.status,200);const d:any=await r.json();assert.equal(d.mode,'dictionary');assert.equal(d.intent.groups.length,2);assert.equal(calls,0);});
await test('Configured AI returns bounded parsed effect groups and no-store response',async()=>{env.OPENAI_API_KEY='fixture-not-a-real-key';calls=0;mode='success';const r=await searchCall({query:'화면이 흔들리면서 빛이 번지는 효과'});assert.equal(r.status,200);const d:any=await r.json();assert.equal(d.mode,'ai');assert.equal(d.intent.groups.length,2);assert.equal(calls,1);assert.equal(r.headers.get('cache-control'),'no-store');});
await test('Search rejects malformed/empty/long query and oversized actual body before provider call',async()=>{calls=0;for(const raw of ['null','[]','{}','{bad',' '.repeat(6001),{query:''},{query:' '.repeat(5)},{query:'x'.repeat(301)},{query:123}])assert.equal((await searchCall(raw)).status,400);assert.equal(calls,0);});
await test('Search rejects cross-origin request before provider call',async()=>{calls=0;assert.equal((await searchCall({query:'glow'},{origin:'https://evil.invalid'})).status,403);assert.equal(calls,0);});
await test('Search exposes useful provider errors without leaking keys',async()=>{for(const value of ['401','429','500','bad']){mode=value;const r=await searchCall({query:'glow'});assert.equal(r.status,422);const d:any=await r.json();assert.equal(typeof d.error,'string');assert(!d.error.includes('fixture-not-a-real-key'));}});
await test('Aborted configured AI request cannot succeed',async()=>{mode='success';const controller=new AbortController();controller.abort();const r=await searchCall({query:'glow'},{},controller.signal);assert.equal(r.status,422);assert((await r.json() as any).error.includes('취소'));});
}finally{globalThis.fetch=originalFetch;delete env.OPENAI_API_KEY;delete env.GEMINI_API_KEY;sql.close();}
console.log(JSON.stringify({passed,failed}));if(failed)process.exitCode=1;
