'use client';
import {useEffect,useLayoutEffect,useMemo,useRef,useState} from 'react';
import {Search,Sparkles,X,Loader2,RotateCcw,Check} from 'lucide-react';
import {SegmentCards} from './segment-library';
import {effectTags,feedbackChoices,intentKey,localEffectIntent,parseIntent,presetIntent,recommendSegments,seedIntent,type EffectIntent,type FeedbackRecord,type FeedbackValue,type Recommendation} from '@/lib/recommendations';
import {tagById,normalizeAlias,namespaceNames} from '@/lib/taxonomy';
import type {SegmentResult} from '@/lib/segment-search';
import type {Clip} from '@/lib/clips';
import type {ClipSegment} from '@/lib/segments';
export type EffectSeed={item:SegmentResult;requestId:number};
async function request<T>(url:string,init?:RequestInit){const res=await fetch(url,init),data=await res.json().catch(()=>({error:'요청을 완료하지 못했어요.'})) as T & {error?:string};if(!res.ok)throw new Error(data.error||'요청을 완료하지 못했어요.');return data;}
export function EffectExplorer({items,seed,onOpen,onFavorite,favoriteBusy,onTag}:{items:SegmentResult[];seed:EffectSeed|null;onOpen:(clip:Clip,segment:ClipSegment)=>void;onFavorite:(clip:Clip,segmentId:string)=>void;favoriteBusy:Set<string>;onTag:(category:'color'|'shot'|'effect',value:string)=>void}){
 const[query,setQuery]=useState(seed?.item.segment.title|| (seed?'이 구간과 비슷한 효과':'')),[intent,setIntent]=useState<EffectIntent>(()=>seed?seedIntent(seed.item):{summary:'',groups:[]}),[exclude,setExclude]=useState(seed?seed.item.clip.id+'/'+seed.item.segment.id:''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[feedback,setFeedback]=useState<{context:string;records:FeedbackRecord[]}>({context:'',records:[]}),[feedbackError,setFeedbackError]=useState(''),[feedbackLoaded,setFeedbackLoaded]=useState(''),[saving,setSaving]=useState<Set<string>>(new Set()),[reload,setReload]=useState(0),[manual,setManual]=useState(''),[feedbackNotice,setFeedbackNotice]=useState('');
 const controller=useRef<AbortController|null>(null),version=useRef(0),feedbackVersion=useRef(0),pending=useRef(new Set<string>()),alive=useRef(true);
 const context=intentKey(intent),feedbackKey=context+'/'+reload,loadingFeedback=context!=='[]'&&feedbackLoaded!==feedbackKey,contextRef=useRef(context);useLayoutEffect(()=>{contextRef.current=context;},[context]);
 function cancel(){version.current++;controller.current?.abort();controller.current=null;setBusy(false);}
 function applyIntent(next:EffectIntent){cancel();setIntent(parseIntent(next));setError('');setExclude('');setFeedbackNotice('');}
 function similar(item:SegmentResult){applyIntent(seedIntent(item));setQuery(item.segment.title||'이 구간과 비슷한 효과');setExclude(item.clip.id+'/'+item.segment.id);}
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;controller.current?.abort();};},[]);
 useEffect(()=>{const c=new AbortController(),id=++feedbackVersion.current;if(context==='[]')return;void request<{feedback:FeedbackRecord[]}>('/api/recommendations/feedback?context='+encodeURIComponent(context),{signal:c.signal}).then(data=>{if(!c.signal.aborted&&id===feedbackVersion.current){setFeedback({context,records:data.feedback});setFeedbackError('');}}).catch(e=>{if(!c.signal.aborted&&id===feedbackVersion.current)setFeedbackError(e.message);}).finally(()=>{if(!c.signal.aborted&&id===feedbackVersion.current)setFeedbackLoaded(feedbackKey);});return()=>c.abort();},[context,feedbackKey]);
 const ranked=useMemo(()=>recommendSegments(items,intent,feedback.context===context?feedback.records:[],exclude),[items,intent,feedback,exclude,context]);
 const exact=ranked.filter(r=>r.kind==='exact'&&r.feedback!=='irrelevant'),near=ranked.filter(r=>r.kind==='similar'&&r.feedback!=='irrelevant'),hidden=ranked.filter(r=>r.feedback==='irrelevant');
 async function search(){if(!query.trim())return;cancel();const id=version.current,c=new AbortController();controller.current=c;setBusy(true);setError('');try{const data=await request<{intent:unknown}>('/api/ai/effect-query',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query}),signal:c.signal});if(id!==version.current)return;setIntent(parseIntent(data.intent));setExclude('');setFeedbackNotice('');}catch(e){if(!c.signal.aborted&&id===version.current)setError((e as Error).message);}finally{if(id===version.current)setBusy(false);}}
 async function vote(item:Recommendation,value:FeedbackValue|null){const key=context,identity=key+'/'+item.clip.id+'/'+item.segment.id;if(pending.current.has(identity))return;pending.current.add(identity);setSaving(new Set(pending.current));feedbackVersion.current++;setFeedbackLoaded(feedbackKey);setFeedbackError('');try{const data=await request<{feedback:FeedbackRecord}>('/api/recommendations/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({intent,clipId:item.clip.id,segmentId:item.segment.id,signature:item.signature,value})});if(alive.current&&contextRef.current===key){feedbackVersion.current++;setReload(n=>n+1);setFeedback(old=>({context:key,records:[...(old.context===key?old.records:[]).filter(f=>f.clipId!==item.clip.id||f.segmentId!==item.segment.id),data.feedback]}));setFeedbackNotice(value==='irrelevant'?'이 구간을 추천에서 숨겼어요. 아래에서 취소할 수 있어요.':value===null?'피드백을 취소했어요.':'피드백을 저장했어요. 같은 검색 조건의 추천 순서에 반영돼요.');}}catch(e){if(alive.current&&contextRef.current===key)setFeedbackError((e as Error).message);}finally{pending.current.delete(identity);if(alive.current)setSaving(new Set(pending.current));}}
 function cards(results:Recommendation[]){return <SegmentCards items={results} onOpen={onOpen} onTag={onTag} onFavorite={onFavorite} favoriteBusy={favoriteBusy} onSimilar={similar} renderFooter={item=>{const row=results.find(r=>r.clip.id===item.clip.id&&r.segment.id===item.segment.id)!;const working=saving.has(context+'/'+row.clip.id+'/'+row.segment.id);return <RecommendationFeedback row={row} working={working} loadingFeedback={loadingFeedback} onVote={vote}/>;}}/>;}
 const matches=manual.trim()?effectTags.filter(t=>[t.display_name,t.id,...t.aliases].some(s=>normalizeAlias(s).includes(normalizeAlias(manual)))).slice(0,12):[];
 return <section className="effect-explorer" aria-label="유사 효과 탐색"><div className="effect-intro"><h2><Sparkles size={20}/>어떤 효과를 찾고 있어요?</h2><p>효과 이름을 몰라도 느낌으로 찾아보세요. 내 보관함에 저장된 구간에서 추천해요.</p></div>
 <form className="effect-search-form" onSubmit={e=>{e.preventDefault();void search();}}><input aria-label="원하는 효과 설명" placeholder="예: 화면이 흔들리면서 확대, 빛이 번지는 느낌" value={query} maxLength={300} onChange={e=>{cancel();setQuery(e.target.value);}}/><button className="primary" disabled={busy||!query.trim()}><Search size={17}/>{busy?'해석 중…':'효과 찾기'}</button></form>
 {busy&&<p className="analysis-running" role="status"><Loader2 size={16} className="spinner"/>원하는 효과를 태그로 정리하고 있어요.<button className="subtle-button" onClick={cancel}>취소</button></p>}{error&&<div className="error" role="alert">{error}<button className="subtle-button" onClick={()=>applyIntent(localEffectIntent(query))}>기본 태그로 찾기</button></div>}
 <div className="effect-presets" aria-label="느낌 선택">{[['dynamic','역동적인'],['dreamy','몽환적인'],['strong','강렬한'],['glow','빛이 번지는']].map(([id,label])=><button className="chip" key={id} onClick={()=>{setQuery(label);applyIntent(presetIntent(id));}}>{label}</button>)}</div>
 <div className="intent-card"><div className="intent-heading"><strong>현재 검색 조건</strong>{intent.groups.length>0&&<button className="subtle-button" onClick={()=>{applyIntent({summary:'',groups:[]});setQuery('');}}>초기화</button>}</div><p>{intent.summary||'느낌을 선택하거나 원하는 효과를 입력해주세요.'}</p><div className="intent-groups">{intent.groups.map((g,i)=><div key={g.label+i}><span className="chip selected">{g.label}<button aria-label={g.label+' 조건 삭제'} onClick={()=>applyIntent({...intent,groups:intent.groups.filter((_,j)=>j!==i)})}><X size={14}/></button></span><small>{g.tagIds.map(id=>tagById.get(id)?.display_name).join(' / ')}</small></div>)}</div>{intent.groups.length>0&&<p className="form-note">조건은 모두 포함해요. 한 조건 안의 태그는 하나만 맞아도 돼요.</p>}
 <details className="intent-editor"><summary>태그 직접 추가 · 수정</summary><p className="form-note">조건을 삭제하고 원하는 태그를 추가할 수 있어요. 최대 5개 조건.</p><input aria-label="추천 조건 태그 검색" placeholder="예: glow, 흔들림, 체커보드" value={manual} maxLength={80} onChange={e=>setManual(e.target.value)}/><div className="intent-tag-options">{matches.map(t=><button key={t.id} disabled={intent.groups.length>=5} onClick={()=>{applyIntent({...intent,groups:[...intent.groups,{label:t.display_name,tagIds:[t.id]}]});setManual('');}}>{t.display_name}<small>{namespaceNames[t.namespace]}</small></button>)}{manual&&!matches.length&&<p className="form-note">사전에 없는 태그예요. 다른 이름이나 효과 설명으로 찾아보세요.</p>}</div></details></div>
 {loadingFeedback&&<p className="form-note" role="status">저장한 피드백을 불러오는 중…</p>}{feedbackLoaded===feedbackKey&&feedbackError&&<div className="error" role="alert">{feedbackError}<button className="subtle-button" onClick={()=>setReload(n=>n+1)}><RotateCcw size={14}/>다시 확인</button></div>}{feedbackNotice&&<p className="save-feedback" role="status">{feedbackNotice}</p>}
 {!!intent.groups.length&&<><p className="form-note recommendation-scope">확정된 구간 태그를 기준으로 찾아요. 피드백은 이 검색 조건에 저장되고, 원래 태그는 바뀌지 않아요.</p><div className="results-heading"><h3>입력한 효과 <span>{exact.length}</span></h3><span>모든 조건 일치</span></div>{exact.length?cards(exact):<p className="recommendation-empty">{near.length?'정확히 일치하는 구간은 없지만, 비슷한 효과의 구간을 찾았어요.':'모든 조건에 맞는 구간이 없어요. 조건을 줄이거나 구간 태그를 분석해보세요.'}</p>}<div className="results-heading"><h3>비슷한 효과 <span>{near.length}</span></h3><span>일부 조건 · 유사한 표현</span></div>{near.length?cards(near):<p className="recommendation-empty">아직 비슷한 효과의 구간이 없어요. 다른 느낌이나 태그로 찾아보세요.</p>}{!!hidden.length&&<details className="hidden-recommendations"><summary>관련 없다고 선택한 구간 {hidden.length}개 · 피드백 변경</summary>{cards(hidden)}</details>}</>}
 </section>;
}

function RecommendationFeedback({row,working,loadingFeedback,onVote}:{row:Recommendation;working:boolean;loadingFeedback:boolean;onVote:(row:Recommendation,value:FeedbackValue|null)=>Promise<void>}){return <div className="recommendation-feedback"><p className="recommendation-reason">{row.reason}</p><span>찾던 효과와 맞나요?</span><div role="group" aria-label={(row.segment.title||'구간')+' 추천 피드백'}>{feedbackChoices.map(choice=><button key={choice.value} aria-pressed={row.feedback===choice.value} disabled={working||loadingFeedback} onClick={()=>void onVote(row,row.feedback===choice.value?null:choice.value)}>{row.feedback===choice.value&&<Check size={13}/>} {choice.label}</button>)}</div>{row.feedback&&<button className="subtle-button" disabled={working} onClick={()=>void onVote(row,null)}>피드백 취소</button>}{working&&<span role="status">저장 중…</span>}</div>;}
