'use client';
import NextImage from 'next/image';
import {SortableCards} from './sortable-cards';
import {retagSegments} from '@/lib/analysis/retag-segments';
import {pendingSegmentTags} from '@/lib/segment-tagging';
import {categoryForTag} from '@/lib/taxonomy';
import {FavoriteButton} from './favorite-button';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import type {SegmentResult} from '@/lib/segment-search';
import {Download,Upload,Scissors,Play,Loader2,Pencil,Check,Sparkles} from 'lucide-react';
import type {Clip} from '@/lib/clips';
import {categories,MAX_FILE_SIZE} from '@/lib/clips';
import {segmentTags,timecode,type ClipSegment} from '@/lib/segments';
import {tagById} from '@/lib/taxonomy';
import {decideTag,emptyTagging} from '@/lib/tagging';
import {exportSegment,videoInfo} from '@/lib/video-export';
import {proxyMedia,type LinkInfo} from '@/lib/links/types';
import {videoProvider} from '@/lib/links/provider';
import {VideoPlayer} from './video-player';
import {TagReview} from './tag-review';
import type {ImageSegmentResult} from '@/lib/image-search';
type Media={segmentId:string;fingerprint:string;file:{url:string;size:number;mime:string;durationSeconds:number;width:number;height:number}|null};
async function api(url:string,init?:RequestInit){const res=await fetch(url,init),body=await res.json().catch(()=>({error:'요청을 완료하지 못했어요.'})) as {error?:string;clip:Clip;segments:Media[];link:LinkInfo;file:Media['file']};if(!res.ok)throw new Error(body.error||'요청을 완료하지 못했어요.');return body;}
async function videoBlob(url:string,signal:AbortSignal){const res=await fetch(url,{signal});if(!res.ok){const body=await res.json().catch(()=>({})) as {error?:string};throw new Error(body.error||'원본 영상을 읽지 못했어요. 원본 파일을 첨부해주세요.');}if(Number(res.headers.get('content-length')||0)>MAX_FILE_SIZE)throw new Error('원본이 25MB보다 커요. 용량을 줄인 파일을 첨부해주세요.');const blob=await res.blob();if(!blob.type.startsWith('video/')||blob.size>MAX_FILE_SIZE)throw new Error('25MB 이하의 원본 영상 파일을 첨부해주세요.');return blob;}
export function SegmentCards({items,onOpen,onTag,onFavorite,favoriteBusy,onSimilar,renderFooter,onReorder}:{onReorder?:(keys:string[])=>Promise<void>;onFavorite:(clip:Clip,segmentId:string)=>void;favoriteBusy:Set<string>;onSimilar?:(item:SegmentResult)=>void;renderFooter?:(item:ImageSegmentResult)=>ReactNode;items:ImageSegmentResult[];onOpen:(clip:Clip,segment:ClipSegment)=>void;onTag:(category:'color'|'shot'|'effect',value:string)=>void}){return <SortableCards className="clip-grid segment-grid" onReorder={onReorder}>{items.map(({clip,segment,tags,imageMatch},i)=><article className="clip-card" key={clip.id+'/'+segment.id} data-sort-key={clip.id+'/'+segment.id}><FavoriteButton compact favorite={!!clip.favoriteSegmentIds?.includes(segment.id)} title={segment.title||`구간 ${i+1}`} busy={favoriteBusy.has(clip.id)} onToggle={()=>onFavorite(clip,segment.id)}/><button className="card-open" onClick={()=>onOpen(clip,segment)} aria-label={`${segment.title||`구간 ${i+1}`} 구간 재생`}><div className="clip-thumbnail">{clip.posterUrl?<NextImage unoptimized width={640} height={360} src={clip.posterUrl} alt="" loading="lazy"/>:<Scissors size={46} color="#777777"/>}<span className="source-label">{timecode(segment.startSeconds)}–{timecode(segment.endSeconds)}</span><span className="play"><Play size={19}/></span></div><div className="card-body">{imageMatch&&<p className="photo-match">사진과 일치 · {imageMatch.labels.join(' · ')}</p>}<p className="segment-source">{clip.title}</p><h3>{segment.title||`구간 ${timecode(segment.startSeconds)}`}</h3>{segment.note&&<p className="segment-excerpt">{segment.note}</p>}<div className="card-date"><span>{(segment.endSeconds-segment.startSeconds).toFixed(1)}초</span><span>{pendingSegmentTags(segment)?`AI 제안 ${pendingSegmentTags(segment)}개`:(segment.tagging?'구간 분석됨':'구간별 태그')}</span></div></div></button><div className="card-tags">{categories.flatMap(category=>tags[category].map(label=><button className="chip" key={category+label} onClick={()=>onTag(category,label)}>#{label}</button>))}</div>{onSimilar&&<button className="similar-button" onClick={()=>onSimilar({clip,segment,tags})}><Sparkles size={15}/>이 효과와 비슷한 클립 더 보기</button>}{renderFooter?.(items[i])}</article>)}</SortableCards>;}
export function SegmentLibrary({clip,onChange,onPlay,onEdit,onFavorite,favoriteBusy}:{onFavorite:(segmentId:string)=>void;favoriteBusy:boolean;clip:Clip;onChange:(clip:Clip)=>void;onPlay:(segment:ClipSegment)=>void;onEdit:()=>void}){
 const[media,setMedia]=useState<Media[]>([]),[error,setError]=useState(''),[message,setMessage]=useState(''),[working,setWorking]=useState(''),[percent,setPercent]=useState(0),[watching,setWatching]=useState('');
 const controller=useRef<AbortController|null>(null),cached=useRef<{source:string;blob:Blob}|null>(null),alive=useRef(true);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;controller.current?.abort();};},[]);
 useEffect(()=>{const c=new AbortController();void api('/api/segment-media/'+clip.id,{signal:c.signal}).then(data=>setMedia(data.segments)).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[clip.id,clip.segments,clip.videoUrl]);
 function start(label:string){controller.current?.abort();const c=new AbortController();controller.current=c;setWorking(label);setError('');setMessage('');setPercent(0);return c;}
 function failure(e:unknown){if(alive.current)setError(e instanceof Error?e.message:'저장하지 못했어요.');}
 function finish(){if(alive.current){setWorking('');controller.current=null;}}
 async function source(signal:AbortSignal){const identity=clip.videoUrl||clip.sourceUrl;if(cached.current?.source===identity)return cached.current.blob;let blob:Blob;if(clip.videoUrl)blob=await videoBlob(clip.videoUrl,signal);else{const data=await api('/api/links/resolve',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:clip.sourceUrl}),signal});const info=(data.link||data) as LinkInfo;if(!info.mediaUrl)throw new Error('이 링크에서는 저장할 원본 파일을 얻지 못했어요. 원본 파일을 첨부하면 구간 영상도 저장할 수 있어요.');blob=await videoBlob(proxyMedia(info.mediaUrl),signal);}cached.current={source:identity,blob};return blob;}
 async function attach(file?:File){const c=start('source');try{setMessage(file?'영상 파일 확인 중…':'원본 영상 불러오는 중…');const blob=file||await source(c.signal);if(!blob.size||blob.size>MAX_FILE_SIZE)throw new Error('25MB 이하의 영상 파일을 선택해주세요.');const info=await videoInfo(blob,c.signal);const body=new FormData();body.set('video',blob,file?.name||'source.mp4');body.set('durationSeconds',String(info.durationSeconds));setMessage('영상 파일 보관 중…');const data=await api('/api/media/'+clip.id,{method:'POST',body,signal:c.signal});if(alive.current){onChange(data.clip);setMessage('영상 파일을 보관했어요. 이제 구간 파일도 저장할 수 있어요.');}}catch(e){failure(e);}finally{finish();}}
 async function saveSegment(segment:ClipSegment){const current=media.find(m=>m.segmentId===segment.id);if(!current){setError('구간 파일 정보를 불러온 후 다시 시도해주세요.');return;}const c=start(segment.id);try{const output=await exportSegment(()=>source(c.signal),segment.startSeconds,segment.endSeconds,c.signal,(value,text)=>{if(alive.current){setPercent(value);setMessage(text);}});const body=new FormData();body.set('video',output.blob,'segment.'+(output.blob.type.includes('webm')?'webm':'mp4'));body.set('fingerprint',current.fingerprint);body.set('durationSeconds',String(output.durationSeconds));body.set('width',String(output.width));body.set('height',String(output.height));setMessage('구간 파일 보관 중…');const data=await api(`/api/segment-media/${clip.id}/${segment.id}`,{method:'POST',body,signal:c.signal});if(alive.current){setMedia(data.segments);setMessage('구간 영상을 저장했어요. 다운로드하거나 다시 재생할 수 있어요.');}}catch(e){failure(e);}finally{finish();}}
 async function retag(selected:ClipSegment[]){const c=start('retag');try{const saved=await retagSegments(clip,selected,c.signal,text=>{if(alive.current)setMessage(text);});if(alive.current){onChange(saved);setMessage(`${selected.length}개 구간의 태그를 갱신했어요. 구간 시간·직접 입력 태그·즐겨찾기는 유지했어요.`);}}catch(e){failure(e);}finally{finish();}}
 async function review(segment:ClipSegment,id:string,status:'accepted'|'rejected'){const c=start('tag');try{const data=await api('/api/clips/'+clip.id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:clip.revision||0,segments:(clip.segments||[]).map(s=>s.id===segment.id?{...s,tagging:decideTag(s.tagging||emptyTagging(),id,status)}:s)}),signal:c.signal});if(alive.current)onChange(data.clip);}catch(e){failure(e);}finally{finish();}}
 const youtube=videoProvider(clip.sourceUrl)?.kind==='youtube';
 return <section className="segment-library"><div className="video-storage"><h3>영상 파일 보관</h3>{clip.videoUrl?<><p className="form-note"><Check size={14}/> 영상 파일 보관됨</p><a className="secondary" href={clip.videoUrl+'?download=1'} download><Download size={16}/>전체 영상 다운로드</a></>:<><p className="form-note">{youtube?'YouTube는 링크와 구간 정보가 저장돼요. 파일 다운로드에는 같은 영상의 원본 첨부가 필요해요.':'접근 가능한 원본을 보관하거나 같은 영상 파일을 첨부하세요. 최대 25MB까지 지원해요.'}</p><div className="segment-actions">{!youtube&&<button className="secondary" disabled={!!working} onClick={()=>void attach()}><Download size={16}/>링크 영상 보관</button>}<label className={'secondary file-attach '+(working?'disabled':'')}><Upload size={16}/>원본 파일 첨부<input type="file" aria-label="저장할 원본 영상 첨부" accept="video/mp4,video/webm,video/quicktime,video/ogg" disabled={!!working} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void attach(file);}}/></label></div></>}</div>
 <div className="segment-heading"><h3>구간 클립 <span>{clip.segments?.length||0}</span></h3><div className="segment-actions">{!!clip.segments?.length&&<button className="secondary" disabled={!!working} onClick={()=>void retag(clip.segments!)}><Sparkles size={15}/>구간 태그 다시 분석</button>}<button className="secondary" disabled={!!working} onClick={onEdit}><Pencil size={15}/>구간 · 태그 편집</button></div></div><p className="form-note">구간 파일은 최대 360p로 저장해요. 변환에는 구간 재생 시간만큼 걸리며, 이 화면을 열어두어야 해요. 한 구간 최대 5분 · 25MB.</p>
 {working&&<div className="segment-progress" role="status"><p><Loader2 size={16} className="spinner"/>{message} {working!=='source'&&working!=='tag'&&working!=='retag'?`${percent}%`:''}</p><button className="secondary" onClick={()=>controller.current?.abort()}>취소</button></div>}{!working&&message&&<p className="save-feedback" role="status">{message}</p>}{error&&<p className="error" role="alert">{error}</p>}
 {!(clip.segments?.length)&&<p className="empty-segments">아직 구간이 없어요. ‘구간 · 태그 편집’에서 추가하거나 전체 영상을 분석해보세요.</p>}
 {(clip.segments||[]).map((s,i)=>{const tags=segmentTags(s),file=media.find(m=>m.segmentId===s.id)?.file;return <article className="segment-saved-row" key={s.id}><div className="segment-favorite-heading"><h4>{s.title||`구간 ${i+1}`}</h4><FavoriteButton compact favorite={!!clip.favoriteSegmentIds?.includes(s.id)} title={s.title||`구간 ${i+1}`} busy={favoriteBusy} onToggle={()=>onFavorite(s.id)}/></div><button className="segment-play" onClick={()=>onPlay(s)}><Play size={16}/>{timecode(s.startSeconds)}–{timecode(s.endSeconds)} 재생</button><div className="segment-tag-groups">{[['color','색감'],['shot','구도'],['effect','효과']].map(([category,label])=><div key={category}><span>{label}</span><div className="chips">{tags[category as 'color'|'shot'|'effect'].length?tags[category as 'color'|'shot'|'effect'].map(t=><span className="chip" key={t}>{t}</span>):<span className="form-note">{s.tagging?.assignments.some(a=>a.status==='suggested'&&categoryForTag(a.tagId)===category)?'AI 제안 검수 대기':s.tagging?'확인된 태그 없음':'구간 태그 분석 필요'}</span>}</div></div>)}</div>{s.note&&<p>{s.note}</p>}<div className="segment-actions"><button className="secondary" disabled={!!working} onClick={()=>void retag([s])}><Sparkles size={15}/>이 구간 태그 분석</button>{file?<><a className="secondary" href={file.url+'&download=1'} download><Download size={15}/>구간 다운로드</a><button className="secondary" onClick={()=>setWatching(watching===s.id?'':s.id)}><Play size={15}/>{watching===s.id?'파일 닫기':'저장된 파일 재생'}</button><span className="form-note">{(file.size/1024/1024).toFixed(1)}MB · {file.width}×{file.height}</span></>:<button className="secondary" disabled={!!working||!media.some(m=>m.segmentId===s.id)} onClick={()=>void saveSegment(s)}><Scissors size={15}/>구간 영상 저장</button>}</div>{file&&watching===s.id&&<VideoPlayer src={file.url}/>}<details className="segment-review" open={pendingSegmentTags(s)>0||undefined}><summary>이 구간의 표준 태그 · AI 제안 {pendingSegmentTags(s)}개</summary>{Object.entries(s.legacyStatus||{}).filter(([id,status])=>status!=='accepted'&&!s.tagging?.assignments.some(a=>a.tagId===id)).map(([id,status])=><div className="taxonomy-row" key={id}><strong>{tagById.get(id)?.display_name}</strong><p className="form-note">기존 영상 분석 · {status==='suggested'?'AI 제안':'제외됨'} · 구간 근거는 재분석으로 확인해주세요.</p><button className="secondary" disabled={!!working} onClick={()=>void review(s,id,'accepted')}>이 구간에 확정</button>{status==='suggested'&&<button className="subtle-button" disabled={!!working} onClick={()=>void review(s,id,'rejected')}>제외</button>}</div>)}<TagReview value={s.tagging||emptyTagging()} onDecision={(id,status)=>void review(s,id,status)} onEvidence={seconds=>onPlay({...s,startSeconds:seconds,endSeconds:Math.min(s.endSeconds,seconds+2)})} disabled={!!working}/></details></article>;})}</section>;
}
