import {bucket,database,type ClipRow} from './server';
import {parseSegments,type ClipSegment} from './segments';
export type SegmentMediaRow={object_key:string;clip_id:string;segment_id:string;fingerprint:string;status:string;mime:string;size:number;duration_ms:number;width:number;height:number;created_at:string};
export const sourceIdentity=(row:ClipRow)=>row.local_asset||row.video_key||row.source_url;
export async function segmentFingerprint(row:ClipRow,segment:ClipSegment){const input=JSON.stringify([sourceIdentity(row),segment.id,segment.startSeconds,segment.endSeconds,'360p-v1']);const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(input));return Array.from(new Uint8Array(hash),n=>n.toString(16).padStart(2,'0')).join('');}
export function mediaUrl(clipId:string,segmentId:string,fingerprint:string){return `/api/segment-media/${encodeURIComponent(clipId)}/${encodeURIComponent(segmentId)}?v=${fingerprint}`;}
export async function segmentMediaList(row:ClipRow){const files=(await database().prepare('SELECT * FROM segment_media WHERE clip_id=? AND status=? ORDER BY created_at DESC, object_key DESC').bind(row.id,'ready').all<SegmentMediaRow>()).results;return Promise.all(parseSegments(JSON.parse(row.segments||'[]')).map(async segment=>{const fingerprint=await segmentFingerprint(row,segment),file=files.find(f=>f.segment_id===segment.id&&f.fingerprint===fingerprint);return{segmentId:segment.id,fingerprint,file:file?{url:mediaUrl(row.id,segment.id,fingerprint),size:file.size,mime:file.mime,durationSeconds:file.duration_ms/1000,width:file.width,height:file.height}:null};}));}
// Failed deletions remain in this table and are retried on a later read/save/delete.
export async function cleanSegmentMedia(clipId:string){
 // Claim only objects whose source/range is no longer referenced at the instant of this SQL statement.
 await database().prepare("UPDATE segment_media SET status='deleting' WHERE clip_id=? AND (status='ready' OR (status='pending' AND created_at<?)) AND NOT EXISTS (SELECT 1 FROM clips c,json_each(c.segments) s WHERE c.id=segment_media.clip_id AND coalesce(c.video_key,c.source_url)=segment_media.source_identity AND json_extract(s.value,'$.id')=segment_media.segment_id AND round(json_extract(s.value,'$.startSeconds')*1000)=segment_media.start_ms AND round(json_extract(s.value,'$.endSeconds')*1000)=segment_media.end_ms)").bind(clipId,new Date(Date.now()-15*60*1000).toISOString()).run();
 await database().prepare("UPDATE segment_media SET status='deleting' WHERE clip_id=? AND status='ready' AND EXISTS (SELECT 1 FROM segment_media newer WHERE newer.clip_id=segment_media.clip_id AND newer.segment_id=segment_media.segment_id AND newer.fingerprint=segment_media.fingerprint AND newer.status='ready' AND (newer.created_at>segment_media.created_at OR (newer.created_at=segment_media.created_at AND newer.object_key>segment_media.object_key)))").bind(clipId).run();
 const files=(await database().prepare("SELECT * FROM segment_media WHERE clip_id=? AND (status='deleting' OR (status='pending' AND created_at<?))").bind(clipId,new Date(Date.now()-15*60*1000).toISOString()).all<SegmentMediaRow>()).results;
 for(const file of files){try{await bucket().delete(file.object_key);await database().prepare('DELETE FROM segment_media WHERE object_key=?').bind(file.object_key).run();}catch{console.warn('Cutnote segment file cleanup will be retried');}}
}
