'use client';
import NextImage from 'next/image';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {ExternalLink,Plus,RefreshCw,Sparkles,Loader2,Play,Compass} from 'lucide-react';
import type {Clip} from '@/lib/clips';
import {discoveryProfile,discoveryIdentity} from '@/features/discovery/discovery-profile';
import type {DiscoveryFormat,DiscoveryResult} from '@/lib/ai/youtube-discovery';
async function fetchSuggestions(format:DiscoveryFormat,refresh:boolean,c:AbortController){let data:DiscoveryResult&{error?:string;code?:string}|undefined;for(let attempt=0;attempt<7;attempt++){const res=await fetch('/api/recommendations/youtube',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({format,refresh}),signal:c.signal});data=await res.json() as DiscoveryResult&{error?:string;code?:string};if(res.status===429&&data.code==='search_busy'&&attempt<6){await new Promise<void>((resolve,reject)=>{if(c.signal.aborted){reject(new Error('취소됨'));return;}const timer=setTimeout(done,5000);function done(){c.signal.removeEventListener('abort',cancel);resolve();}function cancel(){clearTimeout(timer);reject(new Error('취소됨'));}c.signal.addEventListener('abort',cancel,{once:true});});continue;}if(!res.ok)throw new Error(data.error||'추천 검색을 완료하지 못했어요.');break;}return data;}
function YouTubeDiscoverySession({clips,onAdd,format,setFormat}:{clips:Clip[];onAdd:(url:string)=>void;format:DiscoveryFormat;setFormat:(format:DiscoveryFormat)=>void}){
 const[result,setResult]=useState<DiscoveryResult|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState('');
 const profile=useMemo(()=>discoveryProfile(clips),[clips]),controller=useRef<AbortController|null>(null),requestId=useRef(0);
 const performSearch=useCallback((refresh=false)=>{controller.current?.abort();const c=new AbortController();controller.current=c;const version=++requestId.current;const timeout=setTimeout(()=>c.abort(),165000);
  return fetchSuggestions(format,refresh,c).then(data=>{if(version===requestId.current&&!c.signal.aborted&&data)setResult(data);}).catch(e=>{if(version===requestId.current&&controller.current===c)setError(c.signal.aborted?'검색이 오래 걸리고 있어요. 다시 찾아주세요.':e instanceof Error?e.message:'검색을 완료하지 못했어요.');}).finally(()=>{clearTimeout(timeout);if(version===requestId.current&&controller.current===c)setBusy(false);});
 },[format]);
 function search(refresh=false){setBusy(true);setError('');void performSearch(refresh);}
 useEffect(()=>{void performSearch();return()=>{controller.current?.abort();controller.current=null;};},[performSearch]);
 return <section className="youtube-discovery"><div className="discovery-heading"><div><p className="eyebrow">다음 영감 찾기</p><h2>YouTube 영상 추천</h2><p>{profile.sourceCount?`레퍼런스 ${profile.sourceCount}개의 확정 태그와 즐겨찾기를 참고해요.`:'아직 확정된 스타일이 없어 다양한 편집 예시부터 찾아요.'}</p></div><button type="button" className="secondary" onClick={()=>void search(true)} disabled={busy}>{busy?<Loader2 size={16} className="spinner"/>:<RefreshCw size={16}/>}다시 찾기</button></div>
 {profile.tags.length>0&&<div className="discovery-taste"><span>내 스타일</span>{profile.tags.map(t=><span className="chip" key={t.id}>{t.label}</span>)}</div>}
 <div className="discovery-filters" role="group" aria-label="추천 영상 형식"><button type="button" aria-pressed={format==='all'} disabled={busy} onClick={()=>setFormat('all')}>영상 + 쇼츠</button><button type="button" aria-pressed={format==='shorts'} disabled={busy} onClick={()=>setFormat('shorts')}>쇼츠만</button></div>
 <p className="form-note">추천 화면을 열면 YouTube 공개 검색으로 자동으로 찾아요. 결과가 부족하면 연결된 OpenAI 검색으로 보완하며 API 사용량이 발생할 수 있어요. 같은 취향의 결과는 2시간 동안 재사용해요.</p>
 {busy&&<div className="discovery-loading" role="status"><Loader2 size={24} className="spinner"/><strong>{result?'새로운 예시를 찾고 있어요':'내 취향에 맞는 영상과 새로운 스타일을 찾고 있어요'}</strong><p>YouTube 검색 결과와 공개 영상 정보를 확인해요. 잠시 걸릴 수 있어요.</p></div>}
 {error&&<p className="error" role="alert">{error}</p>}
 {result&&<><p className="discovery-stamp">{result.cached?'저장된 추천':'새로 찾은 추천'} · {new Date(result.generatedAt).toLocaleString('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})} · 검색 정보 기준이며 영상 분석 결과는 아니에요.</p>{(['similar','explore'] as const).map(group=>{const items=result.items.filter(item=>item.group===group&&!profile.savedYouTubeIds.includes(item.id));return <section className="discovery-section" key={group}><div className="discovery-section-title"><h3>{group==='similar'?<Sparkles size={20}/>:<Compass size={20}/>} {group==='similar'?(profile.sourceCount?'내 스타일과 비슷한 예시':'먼저 살펴볼 예시'):'새롭게 만나볼 스타일'}</h3><span>{items.length}개</span></div>{items.length?<div className="discovery-grid">{items.map(item=><article className="discovery-card" key={item.id}><a className="discovery-cover" href={item.url} target="_blank" rel="noopener noreferrer" aria-label={item.title+' YouTube에서 보기'}><NextImage unoptimized width={640} height={360} src={item.thumbnail} alt="" loading="lazy"/><span className="discovery-format">{item.shorts?'Shorts':'YouTube'}{item.kind==='tutorial'?' · 튜토리얼':''}</span><span className="play"><Play size={20}/></span></a><div className="discovery-card-body"><a href={item.url} target="_blank" rel="noopener noreferrer"><h4>{item.title}</h4></a><p className="discovery-channel">{item.channel}</p><p className="discovery-reason">{item.reason}</p><div className="discovery-actions"><a href={item.url} target="_blank" rel="noopener noreferrer"><ExternalLink size={14}/>검색 출처 · 영상 보기</a><button type="button" className="secondary" onClick={()=>onAdd(item.url)}><Plus size={15}/>저장 · 분석</button></div></div></article>)}</div>:<p className="discovery-empty">{format==='shorts'?'공개 정보를 확인할 수 있는 새 쇼츠를 찾지 못했어요. 영상 + 쇼츠로 넓혀보세요.':'이 조건의 새로운 예시를 찾지 못했어요. 잠시 후 다시 찾아주세요.'}</p>}</section>;})}</>}
 </section>;
}

export function YouTubeDiscovery(props:{clips:Clip[];onAdd:(url:string)=>void}){const[format,setFormat]=useState<DiscoveryFormat>('all');const identity=discoveryIdentity(discoveryProfile(props.clips));return <YouTubeDiscoverySession key={identity+format} {...props} format={format} setFormat={setFormat}/>;}
