import assert from 'node:assert/strict';
import {sealKey,openKey} from '../../cutnote/lib/ai/crypto';
import {parseAnalysis} from '../../cutnote/lib/analysis/types';
import {videoProvider} from '../../cutnote/lib/links/provider';
import {sampleTimes} from '../../cutnote/lib/analysis/whole-video';
import {parseProposal} from '../../cutnote/lib/ai/result';
import {framesRequest,parseFrameInput,parseFramesResult,generateFrames} from '../../cutnote/lib/ai/openai';
import {videoRequest,parseVideoResult,uploadVideo,googleError,generateVideo} from '../../cutnote/lib/ai/gemini';
const secret=Buffer.from(crypto.getRandomValues(new Uint8Array(32))).toString('base64');
const sealed=await sealKey('test-only-no-real-key',secret);
assert(!sealed.includes('test-only-no-real-key'));
assert.equal(await openKey(sealed,secret),'test-only-no-real-key');
assert.notEqual(await sealKey('test-only-no-real-key',secret),sealed);
await assert.rejects(openKey(sealed,Buffer.alloc(32,5).toString('base64')));
const tampered=JSON.parse(sealed);tampered.data=tampered.data.slice(0,3)+'X'+tampered.data.slice(4);await assert.rejects(openKey(JSON.stringify(tampered),secret));
assert.equal(videoProvider('https://youtu.be/YE7VzlLtp-4?t=3')?.url,'https://www.youtube.com/watch?v=YE7VzlLtp-4');
assert.equal(videoProvider('https://www.youtube.com/shorts/YE7VzlLtp-4')?.kind,'youtube');
assert.equal(videoProvider('https://youtube.com.evil.test/watch?v=YE7VzlLtp-4'),null);
assert.equal(videoProvider('javascript:alert(1)'),null);
assert.equal(videoProvider('https://www.instagram.com/reel/Chunk8-jurw/')?.kind,'instagram');
const long=sampleTimes(600);assert.equal(long.length,120);assert(long[0]<.01&&long.at(-1)!>599.9);assert.equal(sampleTimes(10).length,20);assert.throws(()=>sampleTimes(Infinity));
const input={durationSeconds:10,frames:[{seconds:.001,image:'data:image/jpeg;base64,/9j/AA=='},{seconds:4.98,image:'data:image/jpeg;base64,/9j/AA=='},{seconds:9.95,image:'data:image/jpeg;base64,/9j/AA=='}]};
assert.equal(parseFrameInput(input).frames.length,3);
assert.throws(()=>parseFrameInput({...input,frames:input.frames.slice(0,2)}));
assert.throws(()=>parseFrameInput({...input,frames:input.frames.map(f=>({...f,image:'https://evil.test/key'}))}));
const payload=framesRequest(input);assert.equal(payload.store,false);assert.equal(payload.input[0].content.filter(c=>c.type==='input_image').length,3);assert.equal(payload.text.format.strict,true);
const proposal={segments:[{startSeconds:0,endSeconds:3,effects:['visual_style.digital_glitch'],note:'테스트 구간'}],videoAccessible:true,title:'초록빛 레퍼런스',canonicalTags:[{tagId:'color.blue',aiScore:.95,evidenceMs:[1,9950]}],unclassifiedObservations:[],memo:'밝은 장면의 구도를 참고해요.',observations:['00:00.001 초록 배경으로 시작해요.','00:09.950 원경으로 끝나요.']};
for(const partial of [{videoAccessible:false},{title:''},{canonicalTags:[{tagId:'unknown.tag',aiScore:.9,evidenceMs:[1]}]},{observations:[]},{observations:['근거 없는 설명']}])assert.throws(()=>parseProposal(JSON.stringify({...proposal,...partial})));
const response={status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(proposal)}]}]};
const result=parseFramesResult(response,input);assert.equal(result.report.basis,'full-duration-frames');assert.equal(parseAnalysis(result.report)?.engine,'openai-frames-v1');assert.throws(()=>parseFramesResult({...response,status:'incomplete'},input));
const frameResponse=(partial:Record<string,unknown>)=>({status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify({...proposal,...partial})}]}]});
assert.throws(()=>parseFramesResult(frameResponse({canonicalTags:[{tagId:'color.blue',aiScore:.95,evidenceMs:[5000]}]}),input),/프레임/,'AI evidence must reference a supplied frame');
assert.throws(()=>parseFramesResult(frameResponse({observations:['00:07 전달하지 않은 장면']}),input),/프레임/,'observation timestamps must reference supplied frames');
assert.match(parseFramesResult(frameResponse({observations:['00:10 반올림한 마지막 프레임']}),input).report.notes[1],/^00:09\.950 /,'coarse timestamps are normalized to the matching actual sample');
assert.throws(()=>parseProposal(JSON.stringify({...proposal,observations:['00:10.501 영상 밖 근거']}),10),/영상 길이/);
assert.throws(()=>parseProposal(JSON.stringify({...proposal,observations:['02:00:01 지원 범위 밖 근거']})),/영상 길이/);
assert.throws(()=>parseFramesResult({status:'completed',output:[{type:'message',content:[{type:'refusal',refusal:'Cannot analyze'}]}]},input));
const gem=videoRequest('https://www.youtube.com/watch?v=YE7VzlLtp-4');assert.deepEqual(gem.contents[0].parts[0].videoMetadata,{fps:2});assert(!JSON.stringify(gem).includes('startOffset'));assert(!JSON.stringify(gem).includes('endOffset'));
assert.equal(gem.generationConfig.responseFormat.text.mimeType,'APPLICATION_JSON');
assert(!/"(?:enum|minItems|maxItems|minimum|maximum)":/.test(JSON.stringify(gem.generationConfig.responseFormat.text.schema)),'Gemini response grammar must retain its simplified schema');
assert.match(googleError(402),/선불 크레딧/);assert.match(googleError(400,"Invalid value at generation_config.response_format"),/요청 형식/);assert(!googleError(400).includes('공개 상태'));
const gemResult=parseVideoResult({candidates:[{finishReason:'STOP',content:{parts:[{text:JSON.stringify(proposal)}]}}]});assert.equal(parseAnalysis(gemResult.report)?.basis,'full-video');
assert.throws(()=>parseVideoResult({candidates:[{finishReason:'STOP',content:{parts:[{text:JSON.stringify({...proposal,canonicalTags:[{tagId:'unknown.tag',aiScore:.9,evidenceMs:[1]}]})}]}}]}),/사전에/,'server validation must still reject unknown Gemini tag IDs');
const legacy={engine:'mobileclip-s0-v1',basis:'preview',frameCount:1,analyzedAt:new Date().toISOString(),suggestedTags:{color:[],shot:[],effect:[]},notes:[]};assert.equal(parseAnalysis(legacy)?.basis,'preview');assert.throws(()=>parseAnalysis({...legacy,basis:'full-video'}));
const oldFetch=globalThis.fetch;
globalThis.fetch=async()=>new Response('{}',{status:429});await assert.rejects(generateFrames('not-a-real-key',input,new AbortController().signal),/사용 한도/);
globalThis.fetch=async()=>Response.json({error:{message:'Your prepayment credits are depleted.'}},{status:402});await assert.rejects(generateVideo('not-a-real-key','https://www.youtube.com/watch?v=YE7VzlLtp-4',undefined,new AbortController().signal),/선불 크레딧/);
(globalThis as any).FixedLengthStream=class extends TransformStream{constructor(public size:number){super();}};
const calls:string[]=[];globalThis.fetch=async(url,options)=>{calls.push(String(url));if(String(url).endsWith('/upload/v1beta/files'))return new Response('',{headers:{'x-goog-upload-url':'https://generativelanguage.googleapis.com/upload/session'}});if(String(url).endsWith('/upload/session')){await new Response(options?.body as any).arrayBuffer();return Response.json({file:{name:'files/test',uri:'https://generativelanguage.googleapis.com/v1beta/files/test',state:'FAILED'}});}assert.equal(options?.method,'DELETE');return new Response('');};
await assert.rejects(uploadVideo('not-a-real-key',{body:new Blob(['video']).stream(),size:5,mime:'video/mp4'},new AbortController().signal));assert.equal(calls.at(-1),'https://generativelanguage.googleapis.com/v1beta/files/test');globalThis.fetch=oldFetch;
console.log('PASS: encryption/tampering, provider URLs, full-duration sampling, bounded frame input, OpenAI/Gemini payloads, invalid/refused/truncated output, legacy records, quota error, and temporary upload cleanup.');
