import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {env} from './mock-cloudflare';
import {GET,POST} from '../../cutnote/app/api/segment-media/[id]/[segmentId]/route';
import {POST as attachOriginal} from '../../cutnote/app/api/media/[id]/route';
import {cleanSegmentMedia,segmentFingerprint,segmentMediaList} from '../../cutnote/lib/segment-media';
const sql=new DatabaseSync(':memory:');
for(const name of ['0000_steady_wendell_rand','0001_narrow_xavin','0003_public_psylocke','0004_dear_big_bertha','0005_special_famine'])sql.exec(readFileSync('cutnote/drizzle/'+name+'.sql','utf8'));
env.DB={prepare(query:string){return{bind(...values:any[]){return{async first(){return sql.prepare(query).get(...values)||null;},async all(){return{results:sql.prepare(query).all(...values)};},async run(){return{meta:{changes:Number(sql.prepare(query).run(...values).changes)}};}};}};}};
const objects=new Map<string,{bytes:Uint8Array;type:string}>();let putHook:undefined|(()=>Promise<void>|void),deleteFails=false;
env.BUCKET={async put(key:string,body:any,options:any){objects.set(key,{bytes:new Uint8Array(await new Response(body).arrayBuffer()),type:options.httpMetadata.contentType});await putHook?.();},async delete(key:string){if(deleteFails)throw Error('mock deletion failed');objects.delete(key);},async head(key:string){const x=objects.get(key);if(!x)return null;return{size:x.bytes.length,httpMetadata:{contentType:x.type},writeHttpMetadata(h:Headers){h.set('content-type',x.type);}};},async get(key:string,options?:any){const x=objects.get(key);if(!x)return null;const range=options?.range;return{body:range?x.bytes.slice(range.offset,range.offset+range.length):x.bytes,size:x.bytes.length,httpMetadata:{contentType:x.type},writeHttpMetadata(h:Headers){h.set('content-type',x.type);}};}};
const s=()=>({id:'segment',startSeconds:1,endSeconds:3,title:'segment title',effects:[],note:'',tags:{color:[],shot:[],effect:[]}});
const context={params:Promise.resolve({id:'clip',segmentId:'segment'})};
function reset(){sql.exec('DELETE FROM segment_media');sql.exec('DELETE FROM clips');objects.clear();putHook=undefined;deleteFails=false;sql.prepare('INSERT INTO clips(id,title,source_url,video_key,tags,notes,created_at,segments,revision) VALUES (?,?,?,?,?,?,?,?,?)').run('clip','parent','https://example.org/video','original-key',JSON.stringify({color:[],shot:[],effect:[]}),'','2026-09-29',JSON.stringify([s()]),0);}
const row=()=>sql.prepare('SELECT * FROM clips WHERE id=?').get('clip') as any;
function changeSegment(change:any){sql.prepare('UPDATE clips SET segments=?,revision=revision+1 WHERE id=?').run(JSON.stringify([{...s(),...change}]),'clip');}
async function upload(fp?:string){const form=new FormData();form.set('video',new File([new Uint8Array([0x1a,0x45,0xdf,0xa3,0,0,0,0])],'segment.webm',{type:'video/webm'}));form.set('fingerprint',fp||await segmentFingerprint(row(),s()));form.set('durationSeconds','2');form.set('width','640');form.set('height','360');return POST(new Request('http://localhost/api/segment-media/clip/segment',{method:'POST',body:form}),context);}
const count=()=>Number((sql.prepare('SELECT count(*) n FROM segment_media').get() as any).n);
let passes=0,failures=0;
async function test(name:string,fn:()=>Promise<void>){reset();try{await fn();passes++;console.log('PASS',name);}catch(e){failures++;console.error('FAIL',name,':',(e as Error).message);}}
await test('Successful export lists and plays exact saved file',async()=>{const res=await upload();assert.equal(res.status,201);const list=await segmentMediaList(row());assert(list[0].file);const get=await GET(new Request('http://localhost'+list[0].file.url),context);assert.equal(get.status,200);assert.equal((await get.arrayBuffer()).byteLength,8);assert.equal(count(),1);assert.equal(objects.size,1);});
await test('Metadata-only edit during upload retains export',async()=>{putHook=()=>changeSegment({title:'renamed',note:'changed memo',tags:{color:['blue'],shot:[],effect:[]}});assert.equal((await upload()).status,201);assert.equal(count(),1);assert.equal(objects.size,1);assert((await segmentMediaList(row()))[0].file);});
await test('Range edit during upload rejects publish and removes attempt',async()=>{putHook=()=>changeSegment({startSeconds:1.5});assert.equal((await upload()).status,409);assert.equal(count(),0);assert.equal(objects.size,0);});
await test('Source edit during upload rejects publish and removes attempt',async()=>{putHook=()=>{sql.prepare('UPDATE clips SET video_key=? WHERE id=?').run('replacement-key','clip');};assert.equal((await upload()).status,409);assert.equal(count(),0);assert.equal(objects.size,0);});
await test('Deleted clip during upload rejects publish and removes attempt',async()=>{putHook=()=>{sql.prepare('DELETE FROM clips WHERE id=?').run('clip');};assert.equal((await upload()).status,409);assert.equal(count(),0);assert.equal(objects.size,0);});
await test('Range change rejects old URL and cleans old file',async()=>{assert.equal((await upload()).status,201);const old=(await segmentMediaList(row()))[0].file!.url;changeSegment({endSeconds:4});assert.equal((await GET(new Request('http://localhost'+old),context)).status,409);await cleanSegmentMedia('clip');assert.equal(count(),0);assert.equal(objects.size,0);});
await test('Metadata-only edit preserves URL and file after cleanup',async()=>{await upload();const old=(await segmentMediaList(row()))[0].file!.url;changeSegment({title:'renamed'});await cleanSegmentMedia('clip');assert.equal((await GET(new Request('http://localhost'+old),context)).status,200);assert.equal(count(),1);});
await test('Failed R2 cleanup retains tombstone and succeeds on retry',async()=>{await upload();changeSegment({endSeconds:4});deleteFails=true;await cleanSegmentMedia('clip');assert.equal(count(),1);assert.equal((sql.prepare('SELECT status FROM segment_media').get() as any).status,'deleting');assert.equal((await segmentMediaList(row()))[0].file,null);deleteFails=false;await cleanSegmentMedia('clip');assert.equal(count(),0);assert.equal(objects.size,0);});
await test('Original attachment rejects concurrently edited clip and deletes new R2 object',async()=>{sql.prepare('UPDATE clips SET video_key=NULL WHERE id=?').run('clip');const form=new FormData();form.set('video',new File([new Uint8Array([0,0,0,0,102,116,121,112])],'original.mp4',{type:'video/mp4'}));form.set('durationSeconds','10');putHook=()=>{sql.prepare('UPDATE clips SET notes=?,revision=revision+1 WHERE id=?').run('other screen','clip');};const res=await attachOriginal(new Request('http://localhost/api/media/clip',{method:'POST',body:form}),{params:Promise.resolve({id:'clip'})});assert.equal(res.status,409);assert.equal(row().video_key,null);assert.equal(row().notes,'other screen');assert.equal(objects.size,0);});
await test('REGRESSION: concurrent identical exports leave only one retained object',async()=>{let entered=0,release!:()=>void;const both=new Promise<void>(r=>release=r);putHook=async()=>{if(++entered===2)release();await both;};const responses=await Promise.all([upload(),upload()]);assert(responses.every(r=>r.status===201||r.status===200));assert.equal(count(),1,'duplicate current-fingerprint records must be retired');assert.equal(objects.size,1);});
await test('REGRESSION: submillisecond change normalizes to same range and preserves URL',async()=>{await upload();const old=(await segmentMediaList(row()))[0].file!.url;changeSegment({startSeconds:1.0001});assert.equal((await segmentMediaList(row()))[0].file?.url,old);await cleanSegmentMedia('clip');assert.equal((await GET(new Request('http://localhost'+old),context)).status,200);assert.equal(count(),1);assert.equal(objects.size,1);});
await test('Normalized millisecond range change invalidates and cleans old object',async()=>{await upload();const old=(await segmentMediaList(row()))[0].file!.url;changeSegment({startSeconds:1.0006});assert.equal((await segmentMediaList(row()))[0].file,null);assert.equal((await GET(new Request('http://localhost'+old),context)).status,409);await cleanSegmentMedia('clip');assert.equal(count(),0);assert.equal(objects.size,0);});
await test('Failed duplicate cleanup does not hide winner and retries',async()=>{await upload();deleteFails=true;assert.equal((await upload()).status,201);assert.equal(count(),2);assert.equal((sql.prepare("SELECT count(*) n FROM segment_media WHERE status='ready'").get() as any).n,1);const winner=(await segmentMediaList(row()))[0].file;assert(winner);assert.equal((await GET(new Request('http://localhost'+winner.url),context)).status,200);deleteFails=false;await cleanSegmentMedia('clip');assert.equal(count(),1);assert.equal(objects.size,1);});
console.log(JSON.stringify({passes,failures}));sql.close();if(failures)process.exitCode=1;
