import {object} from '@/lib/json';
import {database,crossOrigin,json,findClip,serialize} from '@/lib/server';
import {parseIntent,intentKey,segmentSignature,recommendationItems} from '@/features/discovery/recommendations';
import {readLimited} from '@/lib/links/fetch';
export async function GET(req:Request){if(crossOrigin(req))return json({error:'현재 페이지에서 다시 확인해주세요.'},403);try{const context=new URL(req.url).searchParams.get('context')||'';if(context.length>5000)throw new Error();const ids=JSON.parse(context);if(!Array.isArray(ids))throw new Error();const intent=parseIntent({summary:'',groups:ids.map(tagIds=>({label:'조건',tagIds}))});const {results}=await database().prepare('SELECT clip_id AS clipId,segment_id AS segmentId,signature,value FROM recommendation_feedback WHERE context_key=? AND value!=?').bind(intentKey(intent),'none').all();return json({feedback:results});}catch{return json({error:'추천 피드백을 불러오지 못했어요. 다시 시도해주세요.'},400);}}
export async function POST(req:Request){
 if(crossOrigin(req))return json({error:'현재 페이지에서 다시 선택해주세요.'},403);
 try{let value:Record<string,unknown>;try{const bytes=await readLimited(new Response(req.body),30000);value=object(JSON.parse(new TextDecoder().decode(bytes)));}catch{return json({error:'피드백 입력을 확인해주세요.'},400);}let intent;try{intent=parseIntent(value?.intent);}catch{return json({error:'효과 검색 조건을 확인해주세요.'},400);}if(!intent.groups.length||typeof value.clipId!=='string'||value.clipId.length>64||typeof value.segmentId!=='string'||value.segmentId.length>64||typeof value.signature!=='string'||value.signature.length>20000||!(value.value===null||value.value==='match'||value.value==='partial'||value.value==='irrelevant'))return json({error:'피드백 선택을 확인해주세요.'},400);
 const row=await findClip(value.clipId);if(!row)return json({error:'영상을 찾지 못했어요.'},404);const item=recommendationItems([serialize(row)]).find(i=>i.segment.id===value.segmentId);if(!item)return json({error:'구간을 찾지 못했어요.'},404);const signature=segmentSignature(item);if(signature!==value.signature)return json({error:'구간 정보가 바뀌었어요. 최신 구간을 불러온 후 다시 선택해주세요.'},409);
 await database().prepare('INSERT INTO recommendation_feedback(context_key,clip_id,segment_id,signature,value,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(context_key,clip_id,segment_id) DO UPDATE SET signature=excluded.signature,value=excluded.value,updated_at=excluded.updated_at').bind(intentKey(intent),value.clipId,value.segmentId,signature,value.value??'none',new Date().toISOString()).run();return json({feedback:{clipId:value.clipId,segmentId:value.segmentId,signature,value:value.value}});
 }catch{return json({error:'피드백을 저장하지 못했어요. 잠시 후 다시 선택해주세요.'},500);}
}
