import {parseSegmentTargets,type SegmentTarget} from '@/features/segments/segment-tagging';
import type {AnalysisProgress,AnalysisReport} from './types';
export type TimedFrame={seconds:number;image:string};
export function sampleTimes(duration:number){if(!Number.isFinite(duration)||duration<.1||duration>7200)throw new Error('전체 구간 분석은 2시간 이하의 영상만 지원해요.');const count=Math.min(120,Math.max(2,Math.ceil(duration*2)));const end=Math.max(.001,duration-.05);return Array.from({length:count},(_,i)=>.001+(end-.001)*i/(count-1));}
export function targetSampleTimes(duration:number,targets:SegmentTarget[]){const parsed=parseSegmentTargets(targets,duration)!;const count=Math.max(2,Math.floor(120/parsed.length));return [...new Set(parsed.flatMap(t=>{const gap=t.endSeconds-t.startSeconds,pad=Math.min(.01,gap/100);const frames=Math.min(count,Math.max(2,Math.ceil(gap*2)));return Array.from({length:frames},(_,i)=>t.startSeconds+pad+(gap-2*pad)*i/(frames-1));}))].sort((a,b)=>a-b);}
function wait(video:HTMLVideoElement,event:'loadedmetadata'|'seeked',signal:AbortSignal,run:()=>void){return new Promise<void>((resolve,reject)=>{const done=(error?:Error)=>{clearTimeout(timer);video.removeEventListener(event,ok);video.removeEventListener('error',fail);signal.removeEventListener('abort',cancel);if(error)reject(error);else resolve();};const ok=()=>done(),fail=()=>done(new Error('영상을 읽지 못했어요. MP4(H.264) 또는 WebM 파일로 시도해주세요.')),cancel=()=>done(new DOMException('분석 취소','AbortError'));const timer=setTimeout(fail,20000);video.addEventListener(event,ok,{once:true});video.addEventListener('error',fail,{once:true});signal.addEventListener('abort',cancel,{once:true});if(signal.aborted)cancel();else run();});}
export async function extractWholeVideo(source:Blob|string,signal:AbortSignal,onProgress:(progress:AnalysisProgress)=>void,targets?:SegmentTarget[]){
 const video=document.createElement('video');video.muted=true;video.playsInline=true;video.preload='auto';const url=typeof source==='string'?source:URL.createObjectURL(source);
 try{await wait(video,'loadedmetadata',signal,()=>{video.src=url;video.load();});const duration=video.duration,times=targets?targetSampleTimes(duration,targets):sampleTimes(duration);const scale=Math.min(1,640/Math.max(video.videoWidth,video.videoHeight)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(video.videoWidth*scale));canvas.height=Math.max(1,Math.round(video.videoHeight*scale));const ctx=canvas.getContext('2d');if(!ctx||!video.videoWidth)throw new Error('분석할 영상 화면을 읽지 못했어요.');const frames:TimedFrame[]=[];
 for(const seconds of times){signal.throwIfAborted();await wait(video,'seeked',signal,()=>{video.currentTime=seconds;});ctx.drawImage(video,0,0,canvas.width,canvas.height);frames.push({seconds,image:canvas.toDataURL('image/jpeg',.7)});onProgress({message:`${targets?'선택한 구간에서':'영상 전체 구간에서'} 프레임 추출 중 · ${frames.length}/${times.length}`,percent:Math.round(frames.length/times.length*60)});}return{frames,durationSeconds:duration};
 }finally{video.pause();video.removeAttribute('src');video.load();if(typeof source!=='string')URL.revokeObjectURL(url);}
}
export async function analyzeWholeVideo(source:Blob|string,signal:AbortSignal,onProgress:(progress:AnalysisProgress)=>void,segmentTargets?:SegmentTarget[]):Promise<{report:AnalysisReport;title:string;memo:string}>{const payload=await extractWholeVideo(source,signal,onProgress,segmentTargets);onProgress({message:`OpenAI가 ${segmentTargets?'선택한 구간의':'전체 구간의'} ${payload.frames.length}개 프레임을 분석하고 있어요.`,percent:65});const res=await fetch('/api/ai/frames',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,segmentTargets}),signal});const data=await res.json() as {report:AnalysisReport;title:string;memo:string;error?:string};if(!res.ok)throw new Error(data.error||'전체 구간을 분석하지 못했어요.');return data;}
