'use client';
import { editManualSegmentTags } from '@/features/segments/segment-tagging';
import { randomId } from '@/lib/id';
import { parseTime,type ClipSegment } from '@/lib/segments';
import { decideTag,emptyTagging } from '@/lib/tagging';
import { Play,Plus,Trash2 } from 'lucide-react';
import { useState } from 'react';
import { TagReview } from '../tagging/tag-review';
import { readSegments,type SegmentDraft } from './segment-drafts';
export function SegmentEditor({value,onChange,onPlay,disabled}:{value:SegmentDraft[];onChange:(value:SegmentDraft[])=>void;onPlay:(segment:ClipSegment)=>void;disabled:boolean}){
 const[error,setError]=useState('');
 function update(id:string,key:keyof SegmentDraft,text:string){setError('');onChange(value.map(s=>s.id===id?{...s,[key]:text,...(['effects','color','shot'].includes(key)?editManualSegmentTags(s,s[key as 'effects'|'color'|'shot'],text,key==='effects'?'effect':key as 'color'|'shot'):{})}:s));}
 return <section className="segment-editor" aria-label="구간 클립 편집"><div className="segment-heading"><h3>구간 클립 <span>{value.length}</span></h3><button type="button" className="secondary" disabled={disabled||value.length>=30} onClick={()=>onChange([...value,{id:randomId(),title:'',start:value.length?value.at(-1)!.end:'0',end:String((parseTime(value.at(-1)?.end||'0')||0)+5),color:'',shot:'',effects:'',note:''}])}><Plus size={15}/>구간 추가</button></div><p className="form-note">구간마다 색감·구도·효과를 따로 검색해요. 아래 입력란은 직접 입력 태그이며 AI 태그는 각 구간의 표준 태그 목록에서 확인·수정해요. 시작·끝은 00:05 또는 5처럼 입력하고, 태그는 쉼표로 구분하세요.</p>
 {!value.length&&<p className="form-note">직접 구간을 추가하거나 전체 영상 분석으로 제안받으세요.</p>}
 {value.map((s,i)=><details className="segment-edit-row" key={s.id} open={value.length===1||undefined}><summary>{s.title||`구간 ${i+1}`} · {s.start}–{s.end}</summary><div className="segment-row-heading"><strong>구간 {i+1}</strong><button type="button" className="subtle-button" disabled={disabled} aria-label={`구간 ${i+1} 삭제`} onClick={()=>onChange(value.filter(v=>v.id!==s.id))}><Trash2 size={16}/></button></div><label className="field">구간 제목<input value={s.title} onChange={e=>update(s.id,'title',e.target.value)} maxLength={120} disabled={disabled}/></label><div className="segment-times"><label className="field">시작<input aria-label={`구간 ${i+1} 시작`} value={s.start} onChange={e=>update(s.id,'start',e.target.value)} disabled={disabled} maxLength={12}/></label><label className="field">끝<input aria-label={`구간 ${i+1} 끝`} value={s.end} onChange={e=>update(s.id,'end',e.target.value)} disabled={disabled} maxLength={12}/></label></div><div className="tag-inputs">{[['color','색감'],['shot','구도'],['effects','효과']].map(([key,label])=><label key={key} className="field">{label}<input aria-label={`구간 ${i+1} ${label}`} value={s[key as 'color'|'shot'|'effects']} onChange={e=>update(s.id,key as keyof SegmentDraft,e.target.value)} placeholder="선택 · 쉼표로 구분" disabled={disabled} maxLength={310}/></label>)}</div><label className="field">구간 메모<textarea value={s.note} onChange={e=>update(s.id,'note',e.target.value)} rows={2} maxLength={500} disabled={disabled}/></label><button type="button" className="secondary" disabled={disabled} onClick={()=>{try{onPlay(readSegments([s])[0]);}catch(error){setError((error as Error).message);}}}><Play size={15}/>이 구간 재생</button><TagReview value={s.tagging||emptyTagging()} onDecision={(id,status)=>onChange(value.map(v=>v.id===s.id?{...v,tagging:decideTag(v.tagging||emptyTagging(),id,status)}:v))} onEvidence={seconds=>onPlay({id:s.id,startSeconds:seconds,endSeconds:Math.min(parseTime(s.end),seconds+2),effects:[],note:''})} disabled={disabled}/></details>)}
 {error&&<p className="error" role="alert">{error}</p>}</section>;
}
